Repository sider/runners, pull requests merged in 2020-10, with the labels that each got.

#1521 [ESLint] Add `eslint-plugin-vue` to default package list
  CHANGELOG.md
  images/eslint/package.json
Labels: dependencies, enhancement, language: javascript

#1505 [cpplint] Provide Sider's recommended set of rules
  CHANGELOG.md
  images/cpplint/Dockerfile
  images/cpplint/Dockerfile.erb
  images/cpplint/sider_recommended_CPPLINT.cfg
  lib/runners.rb
  lib/runners/processor/cpplint.rb
  lib/runners/recommended_config.rb
  sig/polyfill.rbi
  sig/runners/recommended_config.rbi
  test/smokes/cpplint/default/src/cfg/CPPLINT.cfg
  test/smokes/cpplint/default_rules/sider.yml
  test/smokes/cpplint/default_rules/src/bar/test.cpp
  test/smokes/cpplint/default_rules/src/foo/sample.cpp
  test/smokes/cpplint/default_rules/src/foo/sample.h
  test/smokes/cpplint/default_rules/src/foo/utils.h
  test/smokes/cpplint/default_rules_when_cfg_exists/CPPLINT.cfg
  test/smokes/cpplint/default_rules_when_cfg_exists/sider.yml
  test/smokes/cpplint/default_rules_when_cfg_exists/src/bar/test1.cpp
  test/smokes/cpplint/default_rules_when_cfg_exists/src/foo/test2.cpp
  test/smokes/cpplint/expectations.rb
  test/smokes/cpplint/no_line_number/CPPLINT.cfg
  test/smokes/cpplint/option_linelength/CPPLINT.cfg
  test/smokes/cpplint/option_target/CPPLINT.cfg
  test/smokes/cpplint/option_target_multi/CPPLINT.cfg
Labels: enhancement, language: c/c++

#1536 [Misspell] Allow `string` type for `target` option
  CHANGELOG.md
  lib/runners/processor/misspell.rb
Labels: language: misc

#1537 Refactor `ruby/setup-ruby` configuration
  .github/workflows/build.yml
  .github/workflows/bump_analyzers.yml
  .github/workflows/steep.yml
  .github/workflows/steep_old.yml
Labels: dx

#1539 Remove needless `bundle install` for ruby/setup-ruby
  .github/workflows/build.yml
  .github/workflows/bump_analyzers.yml
  .github/workflows/steep.yml
  .github/workflows/steep_old.yml
Labels: dx

#1540 Check if `master` tag of devon_rex is used on release
  Rakefile
Labels: dx

#1557 [stylelint] Add `stylelint-config-recommended-scss`
  CHANGELOG.md
  images/stylelint/package.json
Labels: dependencies, language: css

#1558 Use the exact version for `stylelint-config-recommended-scss`
  images/stylelint/package.json
Labels: bug, dependencies, language: css

#1559 Add Goodcheck rule about `^x.y.z` in package.json
  goodcheck.yml
Labels: dx

#1571 Remove fixed version of `strong_json` gem
  Gemfile
  Gemfile.lock
Labels: dependencies, refactoring, ruby

#1573 Bump strong_json from 2.1.0 to 2.1.2
  Gemfile.lock
Labels: dependencies, ruby

#1580 [RuboCop] Update constraint for v1.0.0
  CHANGELOG.md
  lib/runners/processor/rubocop.rb
  test/smokes/rubocop/expectations.rb
  test/smokes/rubocop/v1.0.0/Gemfile
Labels: language: ruby

#1599 Split test from build workflow on CI
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: dx

#1585 [cpplint] Enable new recommended configuration
  CHANGELOG.md
  images/cpplint/sider_recommended_CPPLINT.cfg
  lib/runners/processor/cpplint.rb
  test/smokes/cpplint/default_rules/src/foo/sample.cpp
  test/smokes/cpplint/default_rules/src/foo/sample.h
  test/smokes/cpplint/expectations.rb
Labels: enhancement, language: c/c++
