Repository sider/runners, pull requests merged in 2020-06, with the labels that each got.

#1141 [Cppcheck] Add smoke test case for misra rules
  test/smokes/cppcheck/addon_misra_rules/sider.yml
  test/smokes/cppcheck/addon_misra_rules/src/config/misra.json
  test/smokes/cppcheck/addon_misra_rules/src/config/misra_rules.txt
  test/smokes/cppcheck/addon_misra_rules/src/foo/test.cpp
  test/smokes/cppcheck/expectations.rb
Labels: language: c/c++

#1166 [Cppcheck] Support "Bug hunting"
  CHANGELOG.md
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
  lib/runners/processor/cppcheck.rb
  test/smokes/cppcheck/bug_hunting_addon/c_sample.c
  test/smokes/cppcheck/bug_hunting_addon/sider.yml
  test/smokes/cppcheck/bug_hunting_project/sider.yml
  test/smokes/cppcheck/bug_hunting_project/src/cpp_sample_1.c++
  test/smokes/cppcheck/bug_hunting_project/src/cpp_sample_2.c++
  test/smokes/cppcheck/bug_hunting_project/src/cpp_sample_3.c++
  test/smokes/cppcheck/bug_hunting_project/test.vcxproj
  test/smokes/cppcheck/bug_hunting_target/sider.yml
  test/smokes/cppcheck/bug_hunting_target/src/bar/c_sample.c
  test/smokes/cppcheck/bug_hunting_target/src/bar/cpp_sample.c++
  test/smokes/cppcheck/bug_hunting_target/src/bar/foo/cpp_sample_0.c++
  test/smokes/cppcheck/bug_hunting_target/src/cpp_sample_1.c++
  test/smokes/cppcheck/bug_hunting_target/src/cpp_sample_2.c++
  test/smokes/cppcheck/expectations.rb
  test/smokes/cppcheck/single_target/sider.yml
Labels: enhancement

#1197 bundle update aws-sdk-kms aws-sdk-s3
  Gemfile.lock
Labels: dependencies, ruby

#1200 [PMD CPD] Analyze multiple languages by default
  CHANGELOG.md
  lib/runners/processor/pmd_cpd.rb
  test/smokes/pmd_cpd/expectations.rb
  test/smokes/pmd_cpd/option_language_c/sider.yml
  test/smokes/pmd_cpd/option_multiple_languages/sider.yml
  test/smokes/pmd_cpd/option_multiple_languages/src/bar/hello_cs.cs
  test/smokes/pmd_cpd/option_multiple_languages/src/bar/hello_dart.dart
  test/smokes/pmd_cpd/option_multiple_languages/src/bar/hello_lua.lua
  test/smokes/pmd_cpd/option_multiple_languages/src/bar/hello_python.py
  test/smokes/pmd_cpd/option_multiple_languages/src/foo/hello_cs.cs
  test/smokes/pmd_cpd/option_multiple_languages/src/foo/hello_dart.dart
  test/smokes/pmd_cpd/option_multiple_languages/src/foo/hello_lua.lua
  test/smokes/pmd_cpd/option_multiple_languages/src/foo/hello_python.py
  test/smokes/pmd_cpd/option_multiple_languages_available/sider.yml
  test/smokes/pmd_cpd/option_multiple_languages_default/bar/hello_cpp.cpp
  test/smokes/pmd_cpd/option_multiple_languages_default/bar/hello_cs.cs
  test/smokes/pmd_cpd/option_multiple_languages_default/bar/hello_dart.dart
  test/smokes/pmd_cpd/option_multiple_languages_default/bar/hello_ecmascript.js
  test/smokes/pmd_cpd/option_multiple_languages_default/bar/hello_go.go
  test/smokes/pmd_cpd/option_multiple_languages_default/bar/hello_java.java
  test/smokes/pmd_cpd/option_multiple_languages_default/bar/hello_kotlin.kt
  test/smokes/pmd_cpd/option_multiple_languages_default/bar/hello_lua.lua
  test/smokes/pmd_cpd/option_multiple_languages_default/bar/hello_php.php
  test/smokes/pmd_cpd/option_multiple_languages_default/bar/hello_python.py
  test/smokes/pmd_cpd/option_multiple_languages_default/bar/hello_ruby.rb
  test/smokes/pmd_cpd/option_multiple_languages_default/bar/hello_swift.swift
  test/smokes/pmd_cpd/option_multiple_languages_default/foo/hello_cpp.cpp
  test/smokes/pmd_cpd/option_multiple_languages_default/foo/hello_cs.cs
  test/smokes/pmd_cpd/option_multiple_languages_default/foo/hello_dart.dart
  test/smokes/pmd_cpd/option_multiple_languages_default/foo/hello_ecmascript.js
  test/smokes/pmd_cpd/option_multiple_languages_default/foo/hello_go.go
  test/smokes/pmd_cpd/option_multiple_languages_default/foo/hello_java.java
  test/smokes/pmd_cpd/option_multiple_languages_default/foo/hello_kotlin.kt
  test/smokes/pmd_cpd/option_multiple_languages_default/foo/hello_lua.lua
  test/smokes/pmd_cpd/option_multiple_languages_default/foo/hello_php.php
  test/smokes/pmd_cpd/option_multiple_languages_default/foo/hello_python.py
  test/smokes/pmd_cpd/option_multiple_languages_default/foo/hello_ruby.rb
  test/smokes/pmd_cpd/option_multiple_languages_default/foo/hello_swift.swift
  test/smokes/pmd_cpd/option_multiple_languages_default/sider.yml
  test/smokes/pmd_cpd/option_multiple_languages_invalid/sider.yml
  test/smokes/pmd_cpd/option_multiple_languages_invalid/src/bar/hello_cs.cs
  test/smokes/pmd_cpd/option_multiple_languages_invalid/src/bar/hello_rust.rs
  test/smokes/pmd_cpd/option_multiple_languages_invalid/src/bar/hello_tcl.tcl
  test/smokes/pmd_cpd/option_multiple_languages_invalid/src/foo/hello_cs.cs
  test/smokes/pmd_cpd/option_multiple_languages_invalid/src/foo/hello_rust.rs
  test/smokes/pmd_cpd/option_multiple_languages_invalid/src/foo/hello_tcl.tcl
  test/smokes/pmd_cpd/option_no_skip_blocks/sider.yml
Labels: enhancement, language: misc

#1206 [Brakeman] Fix warning in Markdown
  CHANGELOG.md
  lib/runners/processor/brakeman.rb
  test/smokes/brakeman/expectations.rb
Labels: bug, language: ruby

#1216 [Rails Best Practices] Fix invalid `line_number`
  CHANGELOG.md
  lib/runners/processor/rails_best_practices.rb
Labels: bug

#1229 Use `File.expand_path()` instead of `Pathname(__dir__).join()`
  lib/runners/analyzers.rb
  sig/polyfill.rbi
Labels: refactoring

#1230 [Rails Best Practices] More info in warning message
  CHANGELOG.md
  lib/runners/processor/rails_best_practices.rb
Labels: language: ruby

#1231 [Rails Best Practices] Add smoke test case for invalid line number
  test/smokes/rails_best_practices/expectations.rb
  test/smokes/rails_best_practices/invalid_line_number/app/views/articles/show.html.erb
Labels: language: ruby

#1240 [Rails Best Practices] Re-challenge to fix invalid line number
  CHANGELOG.md
  images/rails_best_practices/Gemfile
  lib/runners/processor/rails_best_practices.rb
  test/smokes/rails_best_practices/expectations.rb
  test/smokes/rails_best_practices/invalid_line_number/app/views/articles/show.html.erb
Labels: bug
