Repository sider/runners, pull requests merged in 2020-12, with the labels that each got.

#1709 Improve RBS for `Runners::Processor`
  lib/runners/processor.rb
  sig/runners/processor.rbs
  sig/runners/results.rbs
Labels: refactoring

#1710 Fix RBS for `Runners::CPlusPlus`
  lib/runners/cplusplus.rb
  sig/runners/cplusplus.rbs
Labels: refactoring

#1711 Fix RBS for `Runners::Go` and `Runners::Java`
  lib/runners/java.rb
  sig/runners/go.rbs
  sig/runners/java.rbs
Labels: refactoring

#1714 Add Goodcheck rule for TypeScript ESLint
  goodcheck.yml
Labels: dx

#1716 Fix RBS for `Runners::IO` classes
  lib/runners/io.rb
  lib/runners/io/aws_s3.rb
  sig/runners/io.rbs
  sig/runners/io/aws_s3.rbs
Labels: refactoring

#1718 Fix RBS for `Runners::Nodejs`
  sig/runners/nodejs.rbs
  sig/runners/nodejs/constraint.rbs
  sig/runners/nodejs/dependency.rbs
Labels: refactoring

#1721 Remove needless RBS of `ObjectSpace` polyfill
  sig/objspace.rbs
Labels: refactoring

#1722 Improve RBS for `Runners::Options`
  lib/runners/options.rb
  lib/runners/schema/options.rb
  sig/runners/options.rbs
Labels: refactoring

#1723 Fix RBS for modules included by `Runners::Processor`
  lib/runners/ruby.rb
  sig/runners/php.rbs
  sig/runners/python.rbs
  sig/runners/ruby.rbs
  sig/runners/swift.rbs
Labels: refactoring

#1724 Fix RBS for `Runners::Ruby::*` modules/classes
  lib/runners/ruby/gem_installer.rb
  lib/runners/ruby/gem_installer/source.rb
  lib/runners/ruby/gem_installer/spec.rb
  lib/runners/ruby/lockfile_loader/lockfile.rb
  sig/runners/ruby/gem_installer.rbs
  sig/runners/ruby/gem_installer/source.rbs
  sig/runners/ruby/gem_installer/spec.rbs
  sig/runners/ruby/lockfile_loader.rbs
  sig/runners/ruby/lockfile_loader/lockfile.rbs
  sig/runners/ruby/lockfile_parser.rbs
  test/ruby_test.rb
Labels: refactoring

#1725 Fix RBS for `Runners::RecommendedConfig`
  lib/runners/recommended_config.rb
  sig/runners/recommended_config.rbs
Labels: refactoring

#1726 Fix RBS for `Runners::Schema::*` classes
  lib/runners/schema/config.rb
  lib/runners/schema/options.rb
  lib/runners/schema/result.rb
  lib/runners/schema/trace.rb
  sig/runners/schema/config.rbs
  sig/runners/schema/options.rbs
  sig/runners/schema/result.rbs
  sig/runners/schema/trace.rbs
Labels: refactoring

#1729 Fix RBS for `Runners::Processor::Brakeman`
  lib/runners.rb
  lib/runners/command.rb
  lib/runners/processor/brakeman.rb
  lib/runners/ruby.rb
  sig/runners/command.rbs
  sig/runners/processor/brakeman.rbs
  sig/runners/ruby.rbs
  sig/runners/ruby/gem_installer.rbs
  sig/runners/ruby/lockfile_loader/lockfile.rbs
Labels: refactoring

#1730 Fix RBS for `Runners::Processor::Goodcheck`
  lib/runners/processor/goodcheck.rb
  sig/runners/processor/goodcheck.rbs
Labels: refactoring

#1732 Stop overriding `Runners::Ruby#default_gem_specs`
  lib/runners/processor/brakeman.rb
  lib/runners/processor/goodcheck.rb
  lib/runners/processor/haml_lint.rb
  lib/runners/processor/querly.rb
  lib/runners/processor/rails_best_practices.rb
  lib/runners/processor/reek.rb
  lib/runners/processor/rubocop.rb
  lib/runners/ruby.rb
  sig/runners/processor/brakeman.rbs
  sig/runners/processor/goodcheck.rbs
  sig/runners/ruby.rbs
  test/ruby_test.rb
Labels: refactoring

#1733 Fix RBS for `Runners::Processor::Checkstyle`
  lib/runners/processor/checkstyle.rb
  sig/runners/processor/checkstyle.rbs
Labels: refactoring

#1734 Add rake task for `steep stats`
  .github/workflows/steep.yml
  Rakefile
  lib/tasks/steep/stats.rb
Labels: dx

#1735 Fix RBS for `Runners::Processor::HamlLint`
  lib/runners/processor/haml_lint.rb
  sig/runners/processor/haml_lint.rbs
Labels: refactoring

#1736 Fix RBS for `Runners::Processor::Querly`
  lib/runners/processor/querly.rb
  sig/runners/processor/querly.rbs
Labels: refactoring

#1737 Fix RBS for `Runners::Processor::RailsBestPractices`
  lib/runners/processor/rails_best_practices.rb
  sig/runners/processor/rails_best_practices.rbs
Labels: refactoring

#1751 Refactor `Runners::Processor::HamlLint`
  lib/runners/processor/haml_lint.rb
  sig/runners/processor/haml_lint.rbs
Labels: refactoring

#1752 Fix RBS for `Runners::Processor::Reek`
  lib/runners/processor/reek.rb
  sig/runners/processor/reek.rbs
Labels: refactoring

#1753 Fix RBS for `Runners::Processor::RuboCop`
  lib/runners/processor/rubocop.rb
  sig/runners/processor.rbs
  sig/runners/processor/rubocop.rbs
Labels: refactoring

#1754 Remove deprecated `Runners::Ruby#ruby_analyzer_bin` method
  lib/runners/ruby.rb
  sig/runners/ruby.rbs
Labels: refactoring

#1755 Improve `rake steep:stats`
  lib/tasks/steep/stats.rb
Labels: dx

#1756 Fix RBS for `Runners::Kotlin`
  sig/runners/kotlin.rbs
Labels: refactoring

#1757 Fix RBS for `Runners::Processor::ClangTidy`
  lib/runners/processor/clang_tidy.rb
  sig/runners/processor/clang_tidy.rbs
Labels: refactoring

#1760 Fix RBS for `Runners::Processor::CodeSniffer`
  lib/runners/processor/code_sniffer.rb
  sig/runners/processor/code_sniffer.rbs
Labels: refactoring

#1761 Simplify pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  docs/how-to-write-a-new-runner.md
Labels: dx

#1763 Fix RBS for `Runners::Processor::Coffeelint`
  lib/runners/processor/coffeelint.rb
  sig/runners/nodejs.rbs
  sig/runners/processor/coffeelint.rbs
  sig/runners/schema/config.rbs
Labels: refactoring

#1764 Fix RBS for `Runners::Processor::Cppcheck`
  lib/runners/processor/cppcheck.rb
  sig/runners/processor/cppcheck.rbs
Labels: refactoring

#1765 Fix RBS for `Runners::Processor::Cpplint`
  sig/runners/processor/cpplint.rbs
Labels: refactoring

#1766 Fix RBS for `Runners::Processor::Detekt`
  sig/runners/processor/detekt.rbs
Labels: refactoring

#1767 Fix RBS for `Runners::Processor::Eslint`
  lib/runners/processor/eslint.rb
  sig/runners/processor/eslint.rbs
Labels: refactoring

#1768 Fix RBS for `Runners::Processor::Flake8`
  lib/runners/processor/flake8.rb
  sig/runners/processor/flake8.rbs
Labels: refactoring

#1769 Fix RBS for `Runners::Processor::FxCop`
  lib/runners/processor/fxcop.rb
  sig/runners/processor/fxcop.rbs
Labels: refactoring

#1770 Fix RBS for `Runners::Processor::GolangCiLint`
  lib/runners/processor/golangci_lint.rb
  sig/runners/processor/golangci_lint.rbs
Labels: refactoring

#1771 Fix RBS for `Runners::Processor::Hadolint`
  lib/runners/processor/hadolint.rb
  sig/runners/processor/hadolint.rbs
Labels: refactoring

#1772 Fix RBS for `Runners::Processor::Javasee`
  lib/runners/processor/javasee.rb
  sig/runners/processor/javasee.rbs
Labels: refactoring

#1774 Fix RBS for `Runners::Processor::Ktlint`
  lib/runners/processor/ktlint.rb
  sig/runners/processor/ktlint.rbs
Labels: refactoring

#1776 Fix RBS for `Runners::Processor::LanguageTool`
  lib/runners/processor/languagetool.rb
  sig/runners/processor/languagetool.rbs
Labels: refactoring

#1778 Fix RBS when using Retryable
  Steepfile
  lib/runners/shell.rb
  sig/runners/shell.rbs
Labels: refactoring

#1779 Fix RBS when using Rainbow
  Steepfile
  sig/rainbow.rbs
Labels: refactoring

#1780 Fix RBS for `Runners::Processor::Misspell`
  lib/runners/processor/misspell.rb
  sig/runners/processor/misspell.rbs
Labels: refactoring

#1782 Fix RBS for `Runners::Location`
  sig/runners/location.rbs
Labels: refactoring

#1783 Fix RBS for `Runners::Processor::Phinder`
  lib/runners/processor/phinder.rb
  sig/runners/processor/phinder.rbs
Labels: refactoring

#1784 Fix RBS for `Runners::Processor::Phpmd`
  lib/runners/processor/phpmd.rb
  sig/runners/processor/phpmd.rbs
Labels: refactoring

#1775 Add an option to analyze git metadata directory
  CHANGELOG.md
  lib/runners/harness.rb
  lib/runners/processor.rb
  sig/runners/processor.rbs
  test/harness_test.rb
Labels: enhancement

#1785 Fix RBS for `Runners::Processor::PmdCpd`
  lib/runners/processor/pmd_cpd.rb
  sig/rexml.rbs
  sig/runners/processor/pmd_cpd.rbs
Labels: refactoring

#1781 Consider line range in `Runners::Changes#include?`
  CHANGELOG.md
  lib/runners/changes.rb
  lib/runners/location.rb
  sig/runners/changes.rbs
  sig/runners/location.rbs
  test/changes_test.rb
  test/location_test.rb
Labels: bug

#1786 Fix RBS for `Runners::Processor::PmdJava`
  lib/runners/processor/pmd_java.rb
  sig/runners/processor/pmd_java.rbs
Labels: refactoring

#1787 Fix RBS for `Runners::Processor::Pylint`
  lib/runners/processor/pylint.rb
  sig/runners/processor/pylint.rbs
Labels: refactoring

#1788 Fix RBS for `Runners::Processor::RemarkLint`
  lib/runners/processor/remark_lint.rb
  sig/runners/processor/remark_lint.rbs
Labels: refactoring

#1789 Fix RBS for `Runners::Processor::ScssLint`
  lib/runners/processor/scss_lint.rb
  sig/runners/processor/scss_lint.rbs
Labels: refactoring

#1790 Fix RBS for `Runners::Processor::Shellcheck`
  lib/runners/processor/shellcheck.rb
  sig/runners/processor/shellcheck.rbs
Labels: refactoring

#1791 Fix RBS for `Runners::Processor::Stylelint`
  lib/runners/processor/stylelint.rb
  sig/runners/processor/stylelint.rbs
Labels: refactoring

#1792 Fix RBS for `Runners::Processor::Swiftlint`
  lib/runners/processor/swiftlint.rb
  sig/runners/processor/swiftlint.rbs
Labels: refactoring

#1793 Fix RBS for `Runners::Processor::Tslint`
  lib/runners/processor/tslint.rb
  sig/runners/processor/tslint.rbs
Labels: refactoring

#1794 Fix RBS for `Runners::Processor::Tyscan`
  lib/runners/processor/tyscan.rb
  sig/runners/processor/tyscan.rbs
Labels: refactoring

#1795 Fix RBS for `Runners::Config`
  lib/runners/config.rb
  sig/runners/config.rbs
Labels: refactoring

#1796 Fix RBS for `Runners::GitBlameInfo`
  sig/runners/git_blame_info.rbs
Labels: refactoring

#1797 Fix RBS for `Runners::Testing::Smoke`
  lib/runners/testing/smoke.rb
  sig/runners/testing/smoke.rbs
Labels: refactoring

#1798 Fix RBS for `Runners::Issue`
  lib/runners/issue.rb
  lib/runners/processor/clang_tidy.rb
  lib/runners/processor/jshint.rb
  lib/runners/processor/misspell.rb
  lib/runners/processor/phpmd.rb
  lib/runners/processor/pmd_cpd.rb
  lib/runners/processor/pmd_java.rb
  sig/rexml.rbs
  sig/runners/issue.rbs
  sig/runners/processor/pmd_cpd.rbs
Labels: refactoring

#1799 Fix RBS for `Runners::Analyzers`
  lib/runners/analyzer.rb
  sig/runners/analyzers.rbs
Labels: refactoring

#1801 Downgrade Steep to 0.37.0
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#1803 Add `rbs` to Gemfile explicitly
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#1804 Bump bundler from 2.1.4 to 2.2.1
  Gemfile.lock
Labels: dependencies, ruby

#1816 Refactor `Runners::CLI` class
  lib/runners/cli.rb
  sig/module.rbs
  sig/optparse.rbs
  sig/runners/cli.rbs
  test/cli_test.rb
Labels: refactoring

#1818 [PMD Java] NoMethodError: undefined method `gsub' for 2:Integer
  CHANGELOG.md
  lib/runners/processor/pmd_java.rb
  sig/runners/processor/pmd_java.rbs
  test/smokes/pmd_java/config/sideci.yml
Labels: bug, language: java

#1817 Remove unused `locale` gem
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  lib/runners.rb
Labels: dependencies, ruby

#1819 Remove unused `shellwords`
  lib/runners.rb
Labels: dependencies, ruby

#1820 Stop requiring `securerandom`
  lib/runners.rb
  test/test_helper.rb
Labels: refactoring

#1821 [PMD CPD] Remove needless `CGI.unescape_html`
  CHANGELOG.md
  lib/runners.rb
  lib/runners/processor/pmd_cpd.rb
Labels: language: java, refactoring

#1822 Move `base64` to `runners/testing/smoke`
  lib/runners.rb
  lib/runners/testing/smoke.rb
Labels: refactoring

#1823 Move `Runners::Testing::Smoke` to `test/smokes/`
  Steepfile
  bin/runners_smoke
  sig/runners/testing/smoke.rbs
  sig/unification_assertion.rbs
  test/smokes/smoke.rb
  test/testing_smoke_test.rb
Labels: refactoring

#1824 Move `lib/tasks/` → `tasks/`
  Rakefile
  Steepfile
  tasks/bump/analyzers.rb
  tasks/bump/devon_rex.rb
  tasks/docker/timeout_test.rb
  tasks/rbs/update_gems.rb
  tasks/readme/generate.rb
  tasks/steep/stats.rb
Labels: refactoring

#1828 Refactor `bin/runners`
  bin/runners
Labels: refactoring

#1829 Move `RunnersTimeoutError` to `Runners::TimeoutError`
  bin/runners
  lib/runners/errors.rb
  sig/runners/errors.rbs
Labels: refactoring

#1831 Fix Ruby warning on javasee.rb
  lib/runners/processor/javasee.rb
Labels: refactoring

#1830 Refactor Bugsnag configuration on CLI
  bin/runners
  lib/runners/cli.rb
  sig/bugsnag.rbs
  sig/runners/cli.rbs
  test/cli_test.rb
Labels: refactoring

#1832 Refactor AWS SDK setup
  bin/runners
  lib/runners/cli.rb
  sig/aws-sdk-s3.rbs
  sig/runners/cli.rbs
  test/cli_test.rb
Labels: refactoring

#1833 Move `bin/runners` to `exe/runners`
  CHANGELOG.md
  README.md
  exe/runners
  images/Dockerfile.end.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/golangci_lint/Dockerfile
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/misspell/Dockerfile
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/shellcheck/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
Labels: refactoring

#1834 [RuboCop] Add supported gems
  CHANGELOG.md
  lib/runners/processor/rubocop.rb
  sig/runners/processor/rubocop.rbs
  test/processor/rubocop_test.rb
Labels: enhancement, ruby

#1835 [Clang-Tidy] Fix performance issue `Performance/CollectionLiteralInLoop`
  lib/runners/processor/clang_tidy.rb
Labels: language: c/c++

#1836 Rename Rake task files: `.rb` -> `.rake`
  Rakefile
  tasks/bump/analyzers.rake
  tasks/bump/devon_rex.rake
  tasks/docker/timeout_test.rake
  tasks/rbs/update_gems.rake
  tasks/readme/generate.rake
  tasks/steep/stats.rake
Labels: refactoring

#1837 Fix broken `rake default`
  Rakefile
  tasks/steep/check.rake
Labels: refactoring

#1838 Remove needless `__dir__` in Rake tasks
  tasks/bump/analyzers.rake
  tasks/rbs/update_gems.rake
  tasks/readme/generate.rake
Labels: refactoring

#1839 Fix `Lint/ConstantDefinitionInBlock` in `tasks/bump/analyzers.rake`
  tasks/bump/analyzers.rake
Labels: refactoring

#1840 Refactor `Runners::Processor::RailsBestPractices#prepare_config` method a bit
  lib/runners/processor/rails_best_practices.rb
Labels: refactoring

#1841 Move `{docker,dockerfile}:*` rake tasks to `task/{docker,dockerfile}/`
  Rakefile
  tasks/docker/build.rake
  tasks/docker/cli_dummy.rb
  tasks/docker/common.rb
  tasks/docker/push.rake
  tasks/docker/shell.rake
  tasks/docker/smoke.rake
  tasks/docker/timeout_test.rake
  tasks/dockerfile/generate.rake
  tasks/dockerfile/verify.rake
  tasks/dockerfile/verify_devon_rex.rake
Labels: refactoring

#1845 Simplify rake task dependencies
  Rakefile
Labels: refactoring

#1846 Remove unused `zlib`
  lib/runners.rb
Labels: refactoring

#1847 Remove unused `net/http`
  lib/runners.rb
Labels: refactoring

#1848 Simplify requiring `digest`
  lib/runners.rb
Labels: refactoring

#1849 Manage open3 via Bundler
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#1850 Manage psych via Bundler
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#1851 Manage json via Bundler
  Gemfile
  Gemfile.lock
  test/harness_test.rb
Labels: dependencies, ruby

#1852 Manage fileutils via Bundler
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#1854 Manage forwardable via Bundler
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#1855 Manage strscan via Bundler
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#1856 Sort and categorize required gems
  lib/runners.rb
Labels: refactoring

#1857 Move `require "fileutils"`
  lib/runners.rb
Labels: refactoring

#1858 Gemification
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  images/Dockerfile.base.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/golangci_lint/Dockerfile
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/misspell/Dockerfile
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/shellcheck/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
  runners.gemspec
Labels: dependencies, ruby

#1861 Downgrade `spec.required_ruby_version` for Dependabot
  runners.gemspec
Labels: dependencies, ruby

#1862 Revert "Downgrade `spec.required_ruby_version` for Dependabot"
  runners.gemspec
Labels: dependencies, ruby

#1863 Bump outdated gems and more relaxed `required_ruby_version`
  Gemfile.lock
  runners.gemspec
Labels: dependencies, ruby

#1877 Unify `#mktmpdir` and `#mktmpdir_as_pathname` in `Tmpdir` module
  lib/runners/harness.rb
  lib/runners/tmpdir.rb
  sig/runners/tmpdir.rbs
Labels: refactoring
