Repository sider/runners, pull requests merged in 2020-05, with the labels that each got.

#1102 [Refactor] Remove unused `Changes#untracked_paths` method
  lib/runners/changes.rb
  sig/runners.rbi
  test/changes_test.rb
  test/result_test.rb
  test/workspace_test.rb
Labels: refactoring

#1103 [Refactor] Optimize `Changes.calculate` for patches
  lib/runners/changes.rb
  sig/polyfill.rbi
  sig/polyfills/git_diff_parser.rbi
  sig/runners.rbi
Labels: refactoring

#1104 [Refactor] Remove `working_dir` argument from `Changes.calculate`
  lib/runners/changes.rb
  lib/runners/workspace.rb
  sig/runners.rbi
  test/changes_test.rb
Labels: refactoring

#1105 [Refactor] Use head source directory as `Workspace#working_dir`
  lib/runners/workspace.rb
  test/workspace_test.rb
Labels: refactoring

#1113 [Refactor] Remove dependency on `Workspace` from `Processor`
  lib/runners/harness.rb
  lib/runners/processor.rb
  sig/runners.rbi
  test/nodejs_test.rb
  test/processor/phpmd_test.rb
  test/processor/remark_lint_test.rb
  test/processor_test.rb
  test/ruby_test.rb
Labels: refactoring

#1137 [Refactor] Extract `SensitiveFilter` class
  goodcheck.yml
  lib/runners.rb
  lib/runners/cli.rb
  lib/runners/sensitive_filter.rb
  lib/runners/trace_writer.rb
  sig/runners.rbi
  sig/runners/sensitive_filter.rbi
  sig_new/runners/cli.rbs
  sig_new/runners/sensitive_filter.rbs
  sig_new/runners/trace_writer.rbs
  test/cli_test.rb
  test/harness_test.rb
  test/ignoring_test.rb
  test/nodejs_test.rb
  test/processor/phpmd_test.rb
  test/processor/remark_lint_test.rb
  test/processor_test.rb
  test/ruby_test.rb
  test/sensitive_filter_test.rb
  test/shell_test.rb
  test/test_helper.rb
  test/trace_writer_test.rb
  test/workspace_test.rb
Labels: refactoring

#1150 Generated ignoring file sometimes is missing
  CHANGELOG.md
  lib/runners/ignoring.rb
  sig_new/tempfile.rbs
Labels: bug

#1153 Fix ignoring non ASCII filename
  CHANGELOG.md
  lib/runners/ignoring.rb
  test/ignoring_test.rb
Labels: bug

#1154 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#1156 [remark-lint] Fix handling `fatal` output
  CHANGELOG.md
  lib/runners/processor/remark_lint.rb
  test/smokes/remark_lint/expectations.rb
  test/smokes/remark_lint/option_rc_path/config/.remarkrc
Labels: bug, language: markdown

#1122 Support PMD CPD
  .dependabot/config.yml
  .github/workflows/build.yml
  CHANGELOG.md
  README.md
  analyzers.yml
  images/pmd_cpd/Dockerfile
  images/pmd_cpd/Dockerfile.erb
  images/pmd_cpd/pmd_cpd
  images/pmd_cpd/pom.xml
  lib/runners.rb
  lib/runners/processor/pmd_cpd.rb
  test/config_test.rb
  test/smokes/pmd_cpd/broken_sider_yml/sider.yml
  test/smokes/pmd_cpd/broken_sider_yml/src/Main.java
  test/smokes/pmd_cpd/expectations.rb
  test/smokes/pmd_cpd/no_files/placeholder
  test/smokes/pmd_cpd/no_issues/app.java
  test/smokes/pmd_cpd/no_issues/sider.yml
  test/smokes/pmd_cpd/option_encoding_error/hello.eucjp.cs
  test/smokes/pmd_cpd/option_encoding_error/sider.yml
  test/smokes/pmd_cpd/option_encoding_error/こんにちは.sjis.cs
  test/smokes/pmd_cpd/option_encoding_success/bar/baz/こんにちは.sjis.cs
  test/smokes/pmd_cpd/option_encoding_success/bar/hello.eucjp.cs
  test/smokes/pmd_cpd/option_encoding_success/foo/こんにちは.sjis.cs
  test/smokes/pmd_cpd/option_encoding_success/sider.yml
  test/smokes/pmd_cpd/option_files/lib/foo/bar.java
  test/smokes/pmd_cpd/option_files/sider.yml
  test/smokes/pmd_cpd/option_files/src/app.java
  test/smokes/pmd_cpd/option_language_c/sider.yml
  test/smokes/pmd_cpd/option_language_c/src/fizzbuzz_1.c
  test/smokes/pmd_cpd/option_language_c/src/fizzbuzz_2.c
  test/smokes/pmd_cpd/option_language_java/MyApp.java
  test/smokes/pmd_cpd/option_language_java/jp/MyAppJp.java
  test/smokes/pmd_cpd/option_language_java/sider.yml
  test/smokes/pmd_cpd/option_language_ruby/foo/bar/baz/qux.rb
  test/smokes/pmd_cpd/option_language_ruby/sider.yml
  test/smokes/pmd_cpd/option_language_ruby/src/app.rb
  test/smokes/pmd_cpd/option_no_skip_blocks/sider.yml
  test/smokes/pmd_cpd/option_no_skip_blocks/src/fizzbuzz.c
  test/smokes/pmd_cpd/option_skip_duplicate_files/bar/baz/hello.utf8.cs
  test/smokes/pmd_cpd/option_skip_duplicate_files/bar/baz/こんにちは.sjis.cs
  test/smokes/pmd_cpd/option_skip_duplicate_files/bar/こんにちは.1.eucjp.cs
  test/smokes/pmd_cpd/option_skip_duplicate_files/bar/こんにちは.2.eucjp.cs
  test/smokes/pmd_cpd/option_skip_duplicate_files/baz/こんにちは.2.eucjp.cs
  test/smokes/pmd_cpd/option_skip_duplicate_files/foo/こんにちは.2.eucjp.cs
  test/smokes/pmd_cpd/option_skip_duplicate_files/sider.yml
  test/smokes/pmd_cpd/success/app.java
  test/smokes/pmd_cpd/warnings/sider.yml
  test/smokes/pmd_cpd/warnings/src/bar/baz/こんにちは.1.eucjp.cs
  test/smokes/pmd_cpd/warnings/src/bar/こんにちは.1.sjis.cs
  test/smokes/pmd_cpd/warnings/src/bar/こんにちは.2.sjis.cs
  test/smokes/pmd_cpd/warnings/src/baz/こんにちは.2.sjis.cs
  test/smokes/pmd_cpd/warnings/src/foo/こんにちは.2.sjis.cs
Labels: enhancement, language: misc

#1158 Fix no file error in Pylint
  CHANGELOG.md
  lib/runners/processor/pylint.rb
  test/smokes/pylint/expectations.rb
  test/smokes/pylint/no_file/.keep
Labels: bug, language: python
