Repository sider/runners, pull requests merged in 2020-11, with the labels that each got.

#1622 Refactor `Runners::Testing::Smoke.build_pattern` method
  lib/runners/testing/smoke.rb
Labels: refactoring

#1634 Fix warning "assigned but unused variable - stderr"
  lib/runners/processor/cppcheck.rb
  lib/runners/processor/scss_lint.rb
  lib/runners/processor/tslint.rb
Labels: refactoring

#1646 Remove needless SSH key for test
  test/data/ssh_key
  test/workspace_test.rb
Labels: refactoring

#1650 [PHPCS] Allow array for `extensions` and `ignore` options
  CHANGELOG.md
  lib/runners/processor/code_sniffer.rb
  test/smokes/code_sniffer/expectations.rb
  test/smokes/code_sniffer/option_extensions/foo.fcgi
  test/smokes/code_sniffer/option_extensions/foo.inc
  test/smokes/code_sniffer/option_extensions/foo.php
  test/smokes/code_sniffer/option_extensions/sider.yml
  test/smokes/code_sniffer/option_ignore/sider.yml
  test/smokes/code_sniffer/option_ignore/src/baz.php
  test/smokes/code_sniffer/option_ignore/src/foo.php
  test/smokes/code_sniffer/option_ignore/test/bar.php
Labels: enhancement, language: php

#1657 Fix `check_skip` on Actions [skip ci]
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: dx

#1656 Remove `olegtarasov/get-tag@v2` on GitHub Actions
  .github/workflows/notify_build_to_bugsnag.yml
Labels: dx

#1673 Use cat(1) with heredoc for `github.event` to prevent `'` matching error
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: dx

#1686 Remove ignoring strong_json from dependabot
  .github/dependabot.yml
Labels: dependencies, ruby

#1687 [TSLint] Stop updating deps by dependabot
  .github/dependabot.yml
Labels: dependencies, javascript

#1688 Add `issue_count` to the result schema
  CHANGELOG.md
  lib/runners/harness.rb
  lib/runners/results.rb
  lib/runners/schema/result.rb
  lib/runners/testing/smoke.rb
  sig/runners/analyzer.rbs
  sig/runners/harness.rbs
  sig/runners/results.rbs
  sig/time.rbs
  test/results_test.rb
Labels: enhancement
