Repository sider/runners, pull requests merged in 2020-09, with the labels that each got.

#1459 Reconsider `Results::Failure` message
  CHANGELOG.md
  lib/runners/processor/coffeelint.rb
  lib/runners/processor/cppcheck.rb
  lib/runners/processor/cpplint.rb
  lib/runners/processor/eslint.rb
  lib/runners/processor/golangci_lint.rb
  lib/runners/processor/hadolint.rb
  lib/runners/processor/haml_lint.rb
  lib/runners/processor/javasee.rb
  lib/runners/processor/jshint.rb
  lib/runners/processor/pmd_java.rb
  lib/runners/processor/pylint.rb
  lib/runners/processor/scss_lint.rb
  lib/runners/processor/shellcheck.rb
  lib/runners/processor/tslint.rb
  lib/runners/processor/tyscan.rb
  lib/runners/results.rb
  querly.yml
  sig/runners.rbi
  test/smokes/code_sniffer/expectations.rb
  test/smokes/cppcheck/expectations.rb
  test/smokes/eslint/expectations.rb
  test/smokes/golangci_lint/expectations.rb
  test/smokes/haml_lint/expectations.rb
  test/smokes/javasee/expectations.rb
  test/smokes/pmd_java/expectations.rb
  test/smokes/tslint/expectations.rb
  test/smokes/tyscan/expectations.rb
Labels: bug

#1464 Cleanup unused Prettier settings
  .prettierignore
  .prettierrc.yaml
  README.md
Labels: refactoring

#1475 Bump typescript-eslint from 3.9.1 to 4.1.0
  images/eslint/package.json
  test/smokes/eslint/expectations.rb
Labels: dependencies, javascript

#1479 [RuboCop] Add `standard` to optional gem list
  CHANGELOG.md
  lib/runners/processor/rubocop.rb
Labels: enhancement, language: ruby

#1480 [RuboCop] Improve warning messages
  CHANGELOG.md
  lib/runners/processor/rubocop.rb
  test/smokes/rubocop/expectations.rb
  test/smokes/rubocop/unexpected_error/.rubocop.yml
  test/smokes/rubocop/unexpected_error/Gemfile
  test/smokes/rubocop/unexpected_error/backtrace_silencers.rb
  test/smokes/rubocop/unexpected_error/lib/backtrace_silencers2.rb
Labels: bug, language: ruby

#1485 Make generated `Gemfile` content log valid as Ruby
  CHANGELOG.md
  lib/runners/ruby/gem_installer.rb
  test/ruby_test.rb
Labels: language: ruby

#1489 Run update-ca-certificates(8) before analyzing
  CHANGELOG.md
  images/docker-entrypoint.sh
  lib/runners/testing/smoke.rb
Labels: enhancement

#1506 [RuboCop] Update optional gem list
  CHANGELOG.md
  lib/runners/processor/rubocop.rb
Labels: enhancement, language: ruby

#1520 Delete environment variables after used
  CHANGELOG.md
  bin/runners
  images/docker-entrypoint.sh
  lib/runners/cli.rb
  lib/runners/options.rb
  sig/runners.rbi
  sig/runners/options.rbi
  sig/runners/schema/options.rbi
  sig_new/optparse.rbs
  sig_new/runners/cli.rbs
  sig_new/runners/options.rbs
  test/cli_test.rb
  test/harness_test.rb
  test/options_test.rb
  test/sensitive_filter_test.rb
  test/test_helper.rb
  test/workspace_test.rb
Labels: security
