Repository sider/runners, pull requests merged in 2020-07, with the labels that each got.

#1242 [Rails Best Practices] Fix invalid line number
  CHANGELOG.md
  images/rails_best_practices/Gemfile
  lib/runners/processor/rails_best_practices.rb
  test/smokes/rails_best_practices/expectations.rb
  test/smokes/rails_best_practices/invalid_line_number/app/views/articles/show.html.erb
Labels: bug, language: ruby

#1252 Fix Kotlin file extensions
  CHANGELOG.md
  lib/runners.rb
  lib/runners/kotlin.rb
  lib/runners/processor/detekt.rb
  lib/runners/processor/ktlint.rb
Labels: bug, language: kotlin

#1258 Update GitHub Actions by Dependabot
  .github/dependabot.yml
Labels: dependencies

#1257 Allow `location(start_line,start_column)` format
  CHANGELOG.md
  lib/runners/processor/checkstyle.rb
  lib/runners/processor/code_sniffer.rb
  lib/runners/processor/cppcheck.rb
  lib/runners/processor/detekt.rb
  lib/runners/processor/eslint.rb
  lib/runners/processor/flake8.rb
  lib/runners/processor/golangci_lint.rb
  lib/runners/processor/hadolint.rb
  lib/runners/processor/jshint.rb
  lib/runners/processor/ktlint.rb
  lib/runners/processor/pylint.rb
  lib/runners/processor/remark_lint.rb
  lib/runners/processor/scss_lint.rb
  lib/runners/processor/stylelint.rb
  lib/runners/schema/result.rb
  test/smokes/checkstyle/expectations.rb
  test/smokes/code_sniffer/expectations.rb
  test/smokes/code_sniffer/phpcs3/expectations.rb
  test/smokes/cppcheck/expectations.rb
  test/smokes/detekt/expectations.rb
  test/smokes/eslint/expectations.rb
  test/smokes/flake8/expectations.rb
  test/smokes/golangci_lint/expectations.rb
  test/smokes/hadolint/expectations.rb
  test/smokes/jshint/expectations.rb
  test/smokes/ktlint/expectations.rb
  test/smokes/pylint/expectations.rb
  test/smokes/remark_lint/expectations.rb
  test/smokes/scss_lint/expectations.rb
  test/smokes/stylelint/expectations.rb
Labels: enhancement

#1270 [ESLint] Update the default configuration
  CHANGELOG.md
  images/eslint/sider_eslintrc.yml
  lib/runners/processor/eslint.rb
Labels: enhancement, language: javascript

#1271 [ESLint] Pre-install popular configs and plugins
  CHANGELOG.md
  images/Dockerfile.npm.erb
  images/coffeelint/Dockerfile
  images/eslint/Dockerfile
  images/eslint/package.json
  images/jshint/Dockerfile
  images/remark_lint/Dockerfile
  images/stylelint/Dockerfile
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
  test/smokes/eslint/expectations.rb
  test/smokes/eslint/typescript/.eslintrc.yml
  test/smokes/eslint/typescript/package.json
  test/smokes/eslint/typescript/sider.yml
Labels: enhancement, language: javascript

#1272 [stylelint] Pre-install popular configs and plugins
  CHANGELOG.md
  images/stylelint/package.json
  test/smokes/stylelint/analyze-only-css/.stylelintrc.yaml
  test/smokes/stylelint/analyze-only-css/sideci.yml
  test/smokes/stylelint/analyze-only-css/test.css
  test/smokes/stylelint/analyze-only-css/test.less
  test/smokes/stylelint/analyze-only-css/test.scss
  test/smokes/stylelint/analyze-only-css/test.sss
  test/smokes/stylelint/expectations.rb
  test/smokes/stylelint/only_stylelintrc/.stylelintrc.yaml
  test/smokes/stylelint/only_stylelintrc/test.scss
Labels: enhancement, language: css

#1268 [GolangCI-Lint] Add `severity` and `replacement` to issue result
  CHANGELOG.md
  lib/runners/processor/golangci_lint.rb
  test/smokes/golangci_lint/expectations.rb
  test/smokes/golangci_lint/severity/.golangci.yml
  test/smokes/golangci_lint/severity/test.go
Labels: enhancement, language: go

#1290 [ESLint] Set `ecmaVersion:2015` to the default configuration
  CHANGELOG.md
  images/eslint/sider_eslintrc.yml
  test/smokes/eslint/expectations.rb
  test/smokes/eslint/no_config/index.js
Labels: enhancement, language: javascript

#1291 [PHP_CodeSniffer] Remove deprecated `version` option
  CHANGELOG.md
  lib/runners/processor/code_sniffer.rb
  test/smokes/code_sniffer/expectations.rb
  test/smokes/code_sniffer/version_2/app.php
  test/smokes/code_sniffer/version_2/sider.yml
Labels: deprecation, language: php

#1300 Refactor `Issue` and `Location` classes
  lib/runners/issue.rb
  lib/runners/location.rb
  sig/runners/issue.rbi
  sig/runners/location.rbi
Labels: refactoring

#1301 Prevent unexpected error when missing issue ID
  CHANGELOG.md
  lib/runners/harness.rb
  lib/runners/issue.rb
  lib/runners/processor/eslint.rb
  lib/runners/processor/jshint.rb
  lib/runners/processor/ktlint.rb
  lib/runners/results.rb
  sig/runners.rbi
  sig/runners/issue.rbi
  test/issue_test.rb
  test/smokes/ktlint/expectations.rb
  test/smokes/remark_lint/expectations.rb
  test/smokes/remark_lint/success/readme.md
Labels: bug

#1304 [Refactor] Remove `Processor#ensure_files` method
  lib/runners/processor.rb
  lib/runners/processor/goodcheck.rb
  lib/runners/processor/javasee.rb
  lib/runners/processor/misspell.rb
  lib/runners/processor/phinder.rb
  lib/runners/processor/querly.rb
  lib/runners/processor/swiftlint.rb
  lib/runners/processor/tyscan.rb
  sig/polyfill.rbi
  sig/runners.rbi
  test/smokes/javasee/expectations.rb
  test/smokes/phinder/expectations.rb
  test/smokes/tyscan/expectations.rb
Labels: refactoring

#1306 [HAML-Lint] Fix `line: 0`
  CHANGELOG.md
  lib/runners/processor/haml_lint.rb
Labels: bug, language: ruby

#1307 Avoid git-blame when base commit is not given
  CHANGELOG.md
  lib/runners/harness.rb
  test/harness_test.rb
Labels: bug

#1311 [Clang-Tidy] Add log messages
  lib/runners/processor/clang_tidy.rb
  test/smokes/clang_tidy/expectations.rb
  test/smokes/clang_tidy/no_files/.keep
Labels: language: c/c++

#1309 [Brakeman] Syntax highlight for warning message
  CHANGELOG.md
  lib/runners/processor/brakeman.rb
  test/smokes/brakeman/expectations.rb
Labels: language: ruby

#1310 [stylelint] Add `stylelint-order` to pre-installed list
  CHANGELOG.md
  images/stylelint/package.json
  test/smokes/stylelint/expectations.rb
  test/smokes/stylelint/only_stylelintrc/.stylelintrc.yaml
  test/smokes/stylelint/only_stylelintrc/test.css
Labels: enhancement, language: css

#1318 Refactor `HarnessTest` using `Workspace::Git`
  test/harness_test.rb
Labels: refactoring

#1319 Refactor unit tests using `Workspace`
  test/harness_test.rb
  test/ruby_test.rb
  test/test_helper.rb
  test/workspace/file_test.rb
  test/workspace/git_test.rb
  test/workspace/http_test.rb
  test/workspace_test.rb
Labels: refactoring

#1314 [Cppcheck] Support the option `-I`
  CHANGELOG.md
  lib/runners.rb
  lib/runners/cplusplus.rb
  lib/runners/processor/clang_tidy.rb
  lib/runners/processor/cppcheck.rb
  lib/runners/schema/config.rb
  sig/polyfill.rbi
  sig/runners/cplusplus.rbi
  test/smokes/cppcheck/config_string_values/myinclude/テスト.hpp
  test/smokes/cppcheck/config_string_values/sider.yml
  test/smokes/cppcheck/config_string_values/src/test.c
  test/smokes/cppcheck/expectations.rb
  test/smokes/cppcheck/include_path/sider.yml
  test/smokes/cppcheck/include_path/source/baz/myinclude/example1.h
  test/smokes/cppcheck/include_path/source/baz/myinclude/example2.h
  test/smokes/cppcheck/include_path/source/foo/テスト.cp
  test/smokes/cppcheck/include_path/source/myinc/example.h
  test/smokes/cppcheck/include_path/source/test.c++
  test/smokes/cppcheck/include_path/source/サンプル/test.CPP
  test/smokes/cppcheck/include_path/test.CPP
  test/smokes/cppcheck/include_path/テスト/test.CPP
  test/smokes/cppcheck/include_path_default/bar/incl.hh
  test/smokes/cppcheck/include_path_default/sider.yml
  test/smokes/cppcheck/include_path_default/source/baz/myinclude/example1.H
  test/smokes/cppcheck/include_path_default/source/baz/myinclude/example2.H++
  test/smokes/cppcheck/include_path_default/source/foo/テスト.cxx
  test/smokes/cppcheck/include_path_default/source/includes/e/test.ipp
  test/smokes/cppcheck/include_path_default/source/includes/f/test.TCC
  test/smokes/cppcheck/include_path_default/source/includes/g/test.tpp
  test/smokes/cppcheck/include_path_default/source/myinc/a/inc_hh.hh
  test/smokes/cppcheck/include_path_default/source/myinc/b/inc_hxx.HXX
  test/smokes/cppcheck/include_path_default/source/myinc/c/inc_inc.inc
  test/smokes/cppcheck/include_path_default/source/myinc/d/inc_inl.INL
  test/smokes/cppcheck/include_path_default/source/myinc/example.hpp
  test/smokes/cppcheck/include_path_default/source/test.c
  test/smokes/cppcheck/include_path_default/source/test.h
  test/smokes/cppcheck/include_path_default/source/xuq/inclerr.C++
  test/smokes/cppcheck/include_path_default/source/xuq/test.CC
  test/smokes/cppcheck/include_path_default/test.CC
  test/smokes/cppcheck/include_path_default/work/test.CC
Labels: enhancement, language: c/c++

#1321 Refactor unit tests using Git workspace
  test/cli_test.rb
  test/harness_test.rb
  test/test_helper.rb
  test/workspace/git_test.rb
  test/workspace_test.rb
Labels: refactoring

#1323 Fix non-ascii filename on git-diff
  CHANGELOG.md
  lib/runners/workspace/git.rb
  test/workspace/git_test.rb
Labels: bug

#1324 Refactor `Ignoring` class
  Steepfile
  lib/runners/config.rb
  lib/runners/harness.rb
  lib/runners/ignoring.rb
  sig/runners/config.rbi
  sig/runners/ignoring.rbi
  sig_new/runners/config.rbs
  sig_new/runners/ignoring.rbs
  sig_new/runners/workspace.rbs
  test/config_test.rb
  test/ignoring_test.rb
Labels: refactoring

#1325 Improve `IgnoringTest`
  test/ignoring_test.rb
  test/test_helper.rb
Labels: refactoring

#1316 Remove unused HTTP and File workspace
  .github/workflows/build.yml
  Gemfile
  Gemfile.lock
  lib/runners.rb
  lib/runners/ignoring.rb
  lib/runners/options.rb
  lib/runners/schema/options.rb
  lib/runners/testing/smoke.rb
  lib/runners/workspace.rb
  lib/runners/workspace/file.rb
  lib/runners/workspace/git.rb
  lib/runners/workspace/http.rb
  sig/polyfills/rainbow.rbi
  sig/runners/options.rbi
  sig/runners/testing.rbi
  sig/runners/workspace.rbi
  sig_new/runners/options.rbs
  test/options_test.rb
  test/smokes/brakeman/expectations.rb
  test/smokes/checkstyle/expectations.rb
  test/smokes/clang_tidy/expectations.rb
  test/smokes/code_sniffer/expectations.rb
  test/smokes/code_sniffer/phpcs3/expectations.rb
  test/smokes/coffeelint/expectations.rb
  test/smokes/cppcheck/expectations.rb
  test/smokes/cpplint/expectations.rb
  test/smokes/detekt/expectations.rb
  test/smokes/eslint/expectations.rb
  test/smokes/flake8/expectations.rb
  test/smokes/fxcop/expectations.rb
  test/smokes/golangci_lint/expectations.rb
  test/smokes/goodcheck/expectations.rb
  test/smokes/hadolint/expectations.rb
  test/smokes/haml_lint/expectations.rb
  test/smokes/javasee/expectations.rb
  test/smokes/jshint/expectations.rb
  test/smokes/ktlint/expectations.rb
  test/smokes/languagetool/expectations.rb
  test/smokes/misspell/expectations.rb
  test/smokes/phinder/expectations.rb
  test/smokes/phpmd/expectations.rb
  test/smokes/pmd_cpd/expectations.rb
  test/smokes/pmd_java/expectations.rb
  test/smokes/pylint/expectations.rb
  test/smokes/querly/expectations.rb
  test/smokes/rails_best_practices/expectations.rb
  test/smokes/reek/expectations.rb
  test/smokes/remark_lint/expectations.rb
  test/smokes/rubocop/expectations.rb
  test/smokes/scss_lint/expectations.rb
  test/smokes/scss_lint/syntax_error/err.scss
  test/smokes/shellcheck/expectations.rb
  test/smokes/stylelint/expectations.rb
  test/smokes/swiftlint/expectations.rb
  test/smokes/tslint/expectations.rb
  test/smokes/tyscan/expectations.rb
  test/workspace_test.rb
Labels: refactoring

#1350 Refactor workspace
  lib/runners.rb
  lib/runners/workspace.rb
  lib/runners/workspace/git.rb
  sig/polyfill.rbi
  sig/runners/workspace.rbi
  test/workspace/git_test.rb
Labels: refactoring

#1351 Refactor IO classes
  lib/runners/io.rb
  lib/runners/io/aws_s3.rb
  sig/runners/io.rbi
  sig_new/runners/io.rbs
  test/io/aws_s3_test.rb
Labels: refactoring

#1360 Remove needless Gradle installation
  images/Dockerfile.java.erb
  images/checkstyle/Dockerfile
  images/detekt/Dockerfile
  images/ktlint/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
Labels: language: java, refactoring

#1363 Add `config_file` to result
  CHANGELOG.md
  lib/runners/cli.rb
  lib/runners/schema/result.rb
  lib/runners/testing/smoke.rb
  sig/runners/schema.rbi
  sig/runners/testing.rbi
  test/smokes/eslint/expectations.rb
Labels: enhancement
