Repository sider/runners, pull requests merged in 2021-05, with the labels that each got.

#2350 [ESLint] Fix smoke test
  test/smokes/eslint/expectations.rb
Labels: dx, language: javascript

#2349 [PMD CPD] Add a debug code
  images/pmd_cpd/pmd_cpd
Labels: language: misc

#2353 Bump bundler from 2.2.16 to 2.2.17
  CHANGELOG.md
  Gemfile.lock
  runners.gemspec
Labels: dependencies, language: ruby

#2354 Bundle update
  Gemfile.lock
Labels: dependencies, language: ruby

#2352 Revert "[PMD CPD] Add a debug code"
  images/pmd_cpd/pmd_cpd
Labels: language: misc

#2356 [PMD CPD, Metrics CodeClone] Suppress STDOUT logging
  CHANGELOG.md
  lib/runners/processor/pmd_cpd.rb
Labels: language: misc

#2357 [Rails Best Practices] Mark deprecated
  CHANGELOG.md
  README.md
  analyzers.yml
  lib/runners/processor/rails_best_practices.rb
  test/smokes/rails_best_practices/expectations.rb
Labels: deprecation, language: ruby

#2366 Specify max heap size for Java tools
  CHANGELOG.md
  images/Dockerfile.java.erb
  images/checkstyle/Dockerfile
  images/detekt/Dockerfile
  images/ktlint/Dockerfile
  images/metrics_codeclone/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
Labels: language: misc

#2368 Bump devon_rex images from master to 2.43.0
  CHANGELOG.md
  images/Dockerfile.java.erb
  images/Dockerfile.npm.erb
  images/Dockerfile.php.erb
  images/Dockerfile.python.erb
  images/Dockerfile.ruby.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/clang_tidy/Dockerfile.erb
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/fxcop/Dockerfile.erb
  images/golangci_lint/Dockerfile
  images/golangci_lint/Dockerfile.erb
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/hadolint/Dockerfile.erb
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/javasee/Dockerfile.erb
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/languagetool/Dockerfile.erb
  images/metrics_codeclone/Dockerfile
  images/metrics_complexity/Dockerfile
  images/metrics_fileinfo/Dockerfile
  images/metrics_fileinfo/Dockerfile.erb
  images/misspell/Dockerfile
  images/misspell/Dockerfile.erb
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/shellcheck/Dockerfile
  images/shellcheck/Dockerfile.erb
  images/slim_lint/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/swiftlint/Dockerfile.erb
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
Labels: dependencies

#2371 [RuboCop] Fix links
  CHANGELOG.md
  lib/runners/issue.rb
  lib/runners/processor/haml_lint.rb
  lib/runners/processor/rubocop.rb
  lib/runners/processor/slim_lint.rb
  test/smokes/haml_lint/expectations.rb
  test/smokes/rubocop/expectations.rb
  test/smokes/slim_lint/expectations.rb
Labels: bug, language: ruby

#2373 Bump devon_rex images from 2.43.0 to 2.43.1
  CHANGELOG.md
  images/Dockerfile.java.erb
  images/Dockerfile.npm.erb
  images/Dockerfile.php.erb
  images/Dockerfile.python.erb
  images/Dockerfile.ruby.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/clang_tidy/Dockerfile.erb
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/fxcop/Dockerfile.erb
  images/golangci_lint/Dockerfile
  images/golangci_lint/Dockerfile.erb
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/hadolint/Dockerfile.erb
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/javasee/Dockerfile.erb
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/languagetool/Dockerfile.erb
  images/metrics_codeclone/Dockerfile
  images/metrics_complexity/Dockerfile
  images/metrics_fileinfo/Dockerfile
  images/metrics_fileinfo/Dockerfile.erb
  images/misspell/Dockerfile
  images/misspell/Dockerfile.erb
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/shellcheck/Dockerfile
  images/shellcheck/Dockerfile.erb
  images/slim_lint/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/swiftlint/Dockerfile.erb
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
Labels: dependencies

#2375 Bundle update
  Gemfile.lock
Labels: dependencies, language: ruby

#2376 [remark-lint] Fix empty output
  CHANGELOG.md
  lib/runners/processor/remark_lint.rb
Labels: bug, language: markdown

#2377 Address too long warning message
  CHANGELOG.md
  lib/runners/warnings.rb
  sig/runners/warnings.rbs
  test/warnings_test.rb
Labels: bug

#2321 [ESLint] Enable Sider's recommended set of rules
  CHANGELOG.md
  images/eslint/Dockerfile
  images/eslint/Dockerfile.erb
  lib/runners/processor/eslint.rb
  test/smokes/eslint/expectations.rb
  test/smokes/eslint/yarnrc/package.json
  test/smokes/eslint/yarnrc_yml/package.json
Labels: enhancement, language: javascript

#2323 [RuboCop] Enable Sider's recommended set of rules
  CHANGELOG.md
  images/haml_lint/Dockerfile
  images/haml_lint/Dockerfile.erb
  images/rubocop/Dockerfile
  images/rubocop/Dockerfile.erb
  images/slim_lint/Dockerfile
  images/slim_lint/Dockerfile.erb
  lib/runners/rubocop_utils.rb
  test/smokes/rubocop/expectations.rb
  test/smokes/rubocop/v0.71_rails/cat.rb
  test/smokes/rubocop/v0.72_rails/cat.rb
  test/smokes/rubocop/v0.72_rails_option/cat.rb
Labels: enhancement, language: ruby

#2345 [PMD Java] Enable Sider's recommended set of rules
  CHANGELOG.md
  images/pmd_java/Dockerfile
  images/pmd_java/Dockerfile.erb
  lib/runners/processor/pmd_java.rb
  test/smokes/pmd_java/expectations.rb
Labels: enhancement, language: java

#2387 Bundle update
  Gemfile.lock
  runners.gemspec
  test/smokes/eslint/expectations.rb
Labels: dependencies, language: ruby

#2401 Bundle update
  Gemfile.lock
Labels: dependencies, language: ruby
