Repository sider/runners, pull requests merged in 2021-09, with the labels that each got.

#2649 [ESLint] Fix loading config file with ESM mode
  CHANGELOG.md
  lib/runners/processor/eslint.rb
  test/smokes/eslint/esm/index.js
  test/smokes/eslint/esm/package.json
  test/smokes/eslint/expectations.rb
Labels: bug, language: javascript

#2655 Bump devon_rex images from 2.45.9 to 2.45.10
  CHANGELOG.md
  images/Dockerfile.java.erb
  images/Dockerfile.npm.erb
  images/Dockerfile.php.erb
  images/Dockerfile.python.erb
  images/Dockerfile.ruby.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/clang_tidy/Dockerfile.erb
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/fxcop/Dockerfile.erb
  images/golangci_lint/Dockerfile
  images/golangci_lint/Dockerfile.erb
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/hadolint/Dockerfile.erb
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/javasee/Dockerfile.erb
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/languagetool/Dockerfile.erb
  images/metrics_codeclone/Dockerfile
  images/metrics_complexity/Dockerfile
  images/metrics_fileinfo/Dockerfile
  images/metrics_fileinfo/Dockerfile.erb
  images/misspell/Dockerfile
  images/misspell/Dockerfile.erb
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/secret_scan/Dockerfile
  images/shellcheck/Dockerfile
  images/shellcheck/Dockerfile.erb
  images/slim_lint/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/swiftlint/Dockerfile.erb
  images/tyscan/Dockerfile
Labels: dependencies

#2664 Fix wrong version by updating manually
  CHANGELOG.md
  Gemfile.lock
  lib/runners/version.rb
Labels: bug

#2666 Revert "Bump cakephp/cakephp-codesniffer from 3.3.0 to 4.5.1 in /images/code_sniffer"
  CHANGELOG.md
  images/code_sniffer/composer.json
  images/code_sniffer/composer.lock
  test/smokes/code_sniffer/expectations.rb
  test/smokes/code_sniffer/phpcs3/expectations.rb
Labels: bug, dependencies, language: php, priority: high

#2674 Ignore Dependabot updates for `cakephp/cakephp-codesniffer`
  .github/dependabot.yml
Labels: dependencies, language: php

#2677 Change remark-lint changelog
  CHANGELOG.md
Labels: documentation, dx

#2676 Relax `required_ruby_version`
  CHANGELOG.md
  runners.gemspec
Labels: dependencies, language: ruby

#2681 Add a new rule to Recommend rules in Checkstyle
  CHANGELOG.md
  images/checkstyle/sider_recommended_checkstyle.xml
Labels: language: java

#2683 Add .remarkrc.yml to fix dead urls error
  .remarkrc.yml
Labels: language: markdown

#2650 Add actionlint analyzer
  .github/dependabot.yml
  .github/workflows/build.yml
  CHANGELOG.md
  README.md
  analyzers.yml
  images/actionlint/Dockerfile
  images/actionlint/Dockerfile.erb
  images/actionlint/Pipfile
  lib/runners.rb
  lib/runners/processor/actionlint.rb
  sig/runners/processor/actionlint.rbs
  steep_expectations.yml
  test/analyzers_test.rb
  test/config_generator_test.rb
  test/config_test.rb
  test/data/test_generate_with_tools.yml
  test/smokes/actionlint/empty/empty.yml
  test/smokes/actionlint/empty/sider.yml
  test/smokes/actionlint/expectations.rb
  test/smokes/actionlint/ignore/ignore.yml
  test/smokes/actionlint/ignore/sider.yml
  test/smokes/actionlint/multiple/multiple.yml
  test/smokes/actionlint/multiple/sider.yml
  test/smokes/actionlint/multitarget/onclick.yml
  test/smokes/actionlint/multitarget/sider.yml
  test/smokes/actionlint/multitarget/unexpected_key.yml
  test/smokes/actionlint/noissue/noissue.yml
  test/smokes/actionlint/noissue/sider.yml
  test/smokes/actionlint/noproject/.keep
  test/smokes/actionlint/noyaml/.github/workflows/.keep
  test/smokes/actionlint/pyflakes/pyflakes.yml
  test/smokes/actionlint/pyflakes/sider.yml
  test/smokes/actionlint/shellcheck/shellcheck.yml
  test/smokes/actionlint/shellcheck/sider.yml
  test/smokes/actionlint/success/.github/workflows/success.yml
Labels: language: misc

#2714 Set up Problem Matcher for Steep
  .github/steep-matcher.json
  .github/workflows/steep.yml
Labels: dx
