Repository sider/runners, pull requests merged in 2021-06, with the labels that each got.

#2417 Bump devon_rex images from 2.43.2 to 2.43.3
  CHANGELOG.md
  Gemfile.lock
  images/Dockerfile.java.erb
  images/Dockerfile.npm.erb
  images/Dockerfile.php.erb
  images/Dockerfile.python.erb
  images/Dockerfile.ruby.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/clang_tidy/Dockerfile.erb
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/fxcop/Dockerfile.erb
  images/golangci_lint/Dockerfile
  images/golangci_lint/Dockerfile.erb
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/hadolint/Dockerfile.erb
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/javasee/Dockerfile.erb
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/languagetool/Dockerfile.erb
  images/metrics_codeclone/Dockerfile
  images/metrics_complexity/Dockerfile
  images/metrics_fileinfo/Dockerfile
  images/metrics_fileinfo/Dockerfile.erb
  images/misspell/Dockerfile
  images/misspell/Dockerfile.erb
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/shellcheck/Dockerfile
  images/shellcheck/Dockerfile.erb
  images/slim_lint/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/swiftlint/Dockerfile.erb
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
  runners.gemspec
  tasks/bump/devon_rex.rake
Labels: dependencies, language: ruby

#2419 Use the edge version of Goodcheck on Sider
  goodcheck.yml
  sider.yml
Labels: dx

#2418 Introduce Secret Scanning
  .github/dependabot.yml
  .github/workflows/build.yml
  CHANGELOG.md
  README.md
  analyzers.yml
  images/secret_scan/Dockerfile
  images/secret_scan/Dockerfile.erb
  images/secret_scan/Gemfile
  lib/runners.rb
  lib/runners/harness.rb
  lib/runners/options.rb
  lib/runners/processor.rb
  lib/runners/processor/secret_scan.rb
  lib/runners/schema/options.rb
  sig/runners/options.rbs
  sig/runners/processor.rbs
  sig/runners/processor/secret_scan.rbs
  steep_expectations.yml
  test/smoke.rb
  test/smokes/secret_scan/expectations.rb
  test/smokes/secret_scan/no_files/.keep
  test/smokes/secret_scan/success/bad.rb
Labels: enhancement, language: misc

#2423 Fix metrics doc links on README
  CHANGELOG.md
  README.md
  analyzers.yml
Labels: bug

#2428 Bump devon_rex images from 2.43.3 to 2.44.1
  CHANGELOG.md
  images/Dockerfile.java.erb
  images/Dockerfile.npm.erb
  images/Dockerfile.php.erb
  images/Dockerfile.python.erb
  images/Dockerfile.ruby.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/clang_tidy/Dockerfile.erb
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/fxcop/Dockerfile.erb
  images/golangci_lint/Dockerfile
  images/golangci_lint/Dockerfile.erb
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/hadolint/Dockerfile.erb
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/javasee/Dockerfile.erb
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/languagetool/Dockerfile.erb
  images/metrics_codeclone/Dockerfile
  images/metrics_complexity/Dockerfile
  images/metrics_fileinfo/Dockerfile
  images/metrics_fileinfo/Dockerfile.erb
  images/misspell/Dockerfile
  images/misspell/Dockerfile.erb
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/secret_scan/Dockerfile
  images/shellcheck/Dockerfile
  images/shellcheck/Dockerfile.erb
  images/slim_lint/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/swiftlint/Dockerfile.erb
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
  lib/runners/ignoring.rb
Labels: dependencies

#2431 Bump outdated gems via `bundle update`
  Gemfile.lock
Labels: dependencies, language: ruby

#2432 [PMD CPD] Fix supported languages
  CHANGELOG.md
  images/pmd_cpd/build.gradle
  lib/runners/java.rb
  lib/runners/processor/pmd_cpd.rb
  sig/runners/java.rbs
  sig/runners/processor/pmd_cpd.rbs
  steep_expectations.yml
  test/smokes/metrics_codeclone/expectations.rb
  test/smokes/pmd_cpd/expectations.rb
  test/smokes/pmd_cpd/option_multiple_languages_invalid/sider.yml
Labels: bug, language: java, language: misc

#2435 [PHPMD] Replace XML reporter with JSON one
  CHANGELOG.md
  lib/runners/processor/phpmd.rb
Labels: language: php

#2440 Bump pmd-dist from 6.34.0 to 6.35.0
  .github/dependabot.yml
  CHANGELOG.md
  images/pmd_cpd/build.gradle
  test/smokes/metrics_codeclone/expectations.rb
  test/smokes/pmd_cpd/expectations.rb
Labels: dependencies, language: java

#2446 Bump devon_rex images from 2.44.1 to 2.44.2
  CHANGELOG.md
  Gemfile.lock
  images/Dockerfile.java.erb
  images/Dockerfile.npm.erb
  images/Dockerfile.php.erb
  images/Dockerfile.python.erb
  images/Dockerfile.ruby.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/clang_tidy/Dockerfile.erb
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/fxcop/Dockerfile.erb
  images/golangci_lint/Dockerfile
  images/golangci_lint/Dockerfile.erb
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/hadolint/Dockerfile.erb
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/javasee/Dockerfile.erb
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/languagetool/Dockerfile.erb
  images/metrics_codeclone/Dockerfile
  images/metrics_complexity/Dockerfile
  images/metrics_fileinfo/Dockerfile
  images/metrics_fileinfo/Dockerfile.erb
  images/misspell/Dockerfile
  images/misspell/Dockerfile.erb
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/secret_scan/Dockerfile
  images/shellcheck/Dockerfile
  images/shellcheck/Dockerfile.erb
  images/slim_lint/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/swiftlint/Dockerfile.erb
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
  runners.gemspec
Labels: dependencies, language: ruby

#2448 Bundle update
  Gemfile.lock
Labels: dependencies, language: ruby

#2447 PMD CPD performance tuning
  CHANGELOG.md
  lib/runners/processor/pmd_cpd.rb
  sig/runners/processor/pmd_cpd.rbs
Labels: language: java, performance

#2443 [Cppcheck] Provide Sider's recommended set of rules
  CHANGELOG.md
  images/cppcheck/sider_recommended_cppcheck.txt
Labels: enhancement, language: c/c++

#2452 [Secret Scan] Use the latest version of Goodcheck
  CHANGELOG.md
  images/secret_scan/Dockerfile
  images/secret_scan/Dockerfile.erb
  images/secret_scan/Gemfile
  lib/runners/processor/secret_scan.rb
  test/smokes/secret_scan/expectations.rb
Labels: dependencies, language: ruby

#2462 [Secret Scan] Fix `NotImplementedError` with `Runners::ConfigGenerator`
  CHANGELOG.md
  lib/runners/config_generator.rb
  lib/runners/processor.rb
  lib/runners/processor/secret_scan.rb
  test/config_generator_test.rb
Labels: bug, language: misc

#2463 Bundle update
  Gemfile.lock
Labels: dependencies, language: ruby

#2464 Use `docker/login-action`
  .github/workflows/build.yml
Labels: dx

#2466 [hadolint] Fix parsing directory
  CHANGELOG.md
  lib/runners/processor/hadolint.rb
  test/smokes/hadolint/default/Dockerfile/.keep
  test/smokes/hadolint/default/sider.yml
  test/smokes/hadolint/default/sub/Dockerfile/.keep
Labels: bug, language: misc

#2465 Add login to Public ECR
  .github/workflows/build.yml
  CHANGELOG.md
Labels: dx

#2468 Publish Docker images to Amazon ECR Public
  .github/workflows/build.yml
  CHANGELOG.md
  tasks/docker/common.rb
  tasks/docker/push.rake
  tasks/docker/tag.rake
Labels: dx

#2471 Docker login only when publishing
  .github/workflows/build.yml
Labels: dx

#2472 Fix publish bug from #2471
  .github/workflows/build.yml
Labels: bug, dx

#2476 Skip `Discourse/NoChdir` on RuboCopUtilsTest
  test/rubocop_utils_test.rb
Labels: dx

#2475 Replace `devon_rex_haskell` in test data
  test/smokes/hadolint/config_option/Dockerfile
  test/smokes/hadolint/default/src/Dockerfile
  test/smokes/hadolint/multi_dockerfile/1/Dockerfile
  test/smokes/hadolint/multi_dockerfile/2/Dockerfile
  test/smokes/hadolint/multi_dockerfile/Dockerfile.erb
  test/smokes/hadolint/multi_dockerfile/Dockerfile.production
  test/smokes/hadolint/multi_dockerfile/Dockerfile.production.erb
  test/smokes/hadolint/multi_dockerfile/Dockerfile.production.txt
  test/smokes/hadolint/multi_dockerfile/Dockerfile.txt
  test/smokes/hadolint/option_ignore/Dockerfile
  test/smokes/hadolint/option_ignore_multi/Dockerfile
Labels: refactoring

#2487 Fix RuboCopUtilsTest
  test/rubocop_utils_test.rb
Labels: dx

#2486 Remove needless `workdflow_dispatch.branches`
  .github/workflows/bump_analyzers.yml
Labels: refactoring

#2473 [PHPMD] Provide Sider's recommended set of rules
  CHANGELOG.md
  images/phpmd/sider_recommended_phpmd.xml
Labels: enhancement, language: php

#2492 Add exit status constants
  CHANGELOG.md
  Steepfile
  exe/runners
  lib/runners.rb
  lib/runners/exitstatus.rb
  sig/runners/exitstatus.rbs
Labels: enhancement
