Repository sider/runners, pull requests merged in 2021-02, with the labels that each got.

#2004 Bump steep from 0.37.0 to 0.40.0
  .github/workflows/steep.yml
  Gemfile
  Gemfile.lock
  Steepfile
  lib/runners/nodejs.rb
  lib/runners/processor/metrics_fileinfo.rb
  sig/minitest.rbs
  sig/module.rbs
  sig/time.rbs
  sig/uri.rbs
Labels: dependencies, ruby

#2005 Bump rubocop from 1.7.0 to 1.9.1
  Gemfile.lock
Labels: dependencies, ruby

#2007 Use `Processor#analyzer_github` to reduce duplication
  lib/runners/processor/hadolint.rb
  lib/runners/processor/haml_lint.rb
  lib/runners/processor/scss_lint.rb
  lib/runners/processor/shellcheck.rb
  lib/runners/processor/stylelint.rb
  lib/runners/processor/tslint.rb
  test/smokes/scss_lint/expectations.rb
Labels: refactoring

#2008 Sort required modules in runners.rb
  lib/runners.rb
Labels: refactoring

#2011 [ESLint] Fix smoke test about "Parsing error"
  test/smokes/eslint/expectations.rb
Labels: dx

#2010 Verify gem installation in Dockerfiles
  CHANGELOG.md
  images/Dockerfile.ruby.erb
  images/brakeman/Dockerfile
  images/goodcheck/Dockerfile
  images/haml_lint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
Labels: language: ruby

#2009 [HAML-Lint] Improve issue ID and links for RuboCop
  CHANGELOG.md
  lib/runners.rb
  lib/runners/processor.rb
  lib/runners/processor/haml_lint.rb
  lib/runners/processor/rubocop.rb
  lib/runners/rubocop_utils.rb
  lib/runners/ruby.rb
  sig/runners/processor.rbs
  sig/runners/processor/haml_lint.rbs
  sig/runners/processor/rubocop.rbs
  sig/runners/rubocop_utils.rbs
  sig/runners/ruby.rbs
  test/processor_test.rb
  test/rubocop_utils_test.rb
  test/ruby_test.rb
  test/smokes/haml_lint/expectations.rb
  test/smokes/haml_lint/with-inherit-gem/.rubocop.yml
Labels: enhancement, language: ruby

#2013 Add methods to `Runners::RuboCopUtils`
  lib/runners/processor/haml_lint.rb
  lib/runners/processor/rubocop.rb
  lib/runners/rubocop_utils.rb
  sig/runners/processor/haml_lint.rbs
  sig/runners/processor/rubocop.rbs
  sig/runners/rubocop_utils.rbs
  test/smokes/rubocop/expectations.rb
  test/smokes/rubocop/plugins/.rubocop.yml
  test/smokes/rubocop/plugins/Gemfile
  test/smokes/rubocop/plugins/foo.rb
Labels: language: ruby, refactoring

#2015 Delete fileutils.rbs
  sig/fileutils.rbs
Labels: refactoring

#2016 Refactor Dockerfiles
  images/Dockerfile.base.erb
  images/Dockerfile.npm.erb
  images/Dockerfile.python.erb
  images/Dockerfile.ruby.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/clang_tidy/Dockerfile.erb
  images/code_sniffer/Dockerfile
  images/code_sniffer/Dockerfile.erb
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/fxcop/Dockerfile.erb
  images/golangci_lint/Dockerfile
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/javasee/Dockerfile.erb
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/metrics_codeclone/Dockerfile
  images/metrics_complexity/Dockerfile
  images/metrics_fileinfo/Dockerfile
  images/misspell/Dockerfile
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/shellcheck/Dockerfile
  images/stylelint/Dockerfile
  images/stylelint/Dockerfile.erb
  images/swiftlint/Dockerfile
  images/swiftlint/Dockerfile.erb
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
Labels: docker, refactoring

#2019 [Metrics Complexity] Run as single thread to avoid timeout error
  CHANGELOG.md
  lib/runners/processor/metrics_complexity.rb
Labels: oriental

#2025 Not support alpha, beta, and rc versions for `rake bump:analyzers`
  tasks/bump/analyzers.rake
Labels: dx

#2027 Refactor loading `Runners::Processor` classes
  lib/runners/cli.rb
  lib/runners/processor.rb
  sig/optparse.rbs
  sig/runners/cli.rbs
  sig/runners/processor.rbs
  test/cli_test.rb
  test/harness_test.rb
  test/java_test.rb
  test/processor_test.rb
  test/rubocop_utils_test.rb
  test/ruby_test.rb
Labels: refactoring

#2031 Bump steep from 0.40.0 to 0.41.0
  Gemfile.lock
Labels: dependencies, ruby

#2032 Save and check `steep_expectations.yml`
  .github/workflows/steep.yml
  lib/runners/cli.rb
  lib/runners/issue.rb
  lib/runners/processor.rb
  lib/runners/processor/checkstyle.rb
  lib/runners/processor/misspell.rb
  lib/runners/processor/shellcheck.rb
  lib/runners/ruby/gem_installer/spec.rb
  sig/bugsnag.rbs
  steep_expectations.yml
  tasks/steep/check.rake
Labels: dx

#2035 Remove needless `continue-on-error: true` on Steep check
  .github/workflows/steep.yml
Labels: dx

#2037 Bump AWS SDK gems
  Gemfile.lock
Labels: dependencies, ruby

#2041 Extract `Runners::Config#field_path` method
  lib/runners/config.rb
  lib/runners/processor.rb
  sig/runners/config.rbs
  sig/runners/processor.rbs
  steep_expectations.yml
  test/config_test.rb
Labels: refactoring

#2042 [HAML-Lint] Fix logic about `parallel` option
  CHANGELOG.md
  lib/runners/processor/haml_lint.rb
  test/processor/haml_lint_test.rb
  test/smokes/haml_lint/expectations.rb
  test/smokes/haml_lint/lowest-deps/sider.yml
Labels: bug, language: ruby

#2043 Remove custom skip-ci
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: refactoring

#2045 Add `bin/setup` and simplify README
  README.md
  bin/setup
Labels: dx

#2046 [Slim-Lint] Set up recommended ruleset
  CHANGELOG.md
  images/slim_lint/Dockerfile
  images/slim_lint/Dockerfile.erb
  images/slim_lint/sider_recommended_slim_lint.yml
  lib/runners/processor/slim_lint.rb
  sig/runners/processor/slim_lint.rbs
  test/smokes/slim_lint/default_config/foo.slim
  test/smokes/slim_lint/expectations.rb
  test/smokes/slim_lint/success/foo.slim
Labels: language: ruby

#2047 Remove needless Querly rule: `sider.runners.exitstatus`
  querly.yml
Labels: dx

#2048 [HAML-Lint] Set up recommended ruleset
  CHANGELOG.md
  images/haml_lint/Dockerfile
  images/haml_lint/Dockerfile.erb
  images/haml_lint/sider_recommended_haml_lint.yml
  lib/runners/processor/haml_lint.rb
  sig/runners/processor/haml_lint.rbs
  test/smokes/haml_lint/expectations.rb
  test/smokes/haml_lint/success/test.haml
  test/smokes/haml_lint/with_exclude_files/hello.haml
Labels: language: ruby

#2050 [Metrics Code Clone] Fix analysis failure with Lexical error
  CHANGELOG.md
  lib/runners/processor/metrics_codeclone.rb
  lib/runners/processor/pmd_cpd.rb
  sig/runners/processor/pmd_cpd.rbs
  test/smokes/metrics_codeclone/expectations.rb
Labels: bug, oriental

#2061 Bump rbs from 1.0.4 to 1.0.5
  Gemfile.lock
  sig/uri.rbs
Labels: dependencies, ruby

#2062 [GolangCI-Lint] Refactor `Runners::Processor::GolangCiLint`
  lib/runners/processor/golangci_lint.rb
Labels: language: go, refactoring

#2063 [GolangCI-Lint] Fix too short timeout value
  CHANGELOG.md
  lib/runners/processor/golangci_lint.rb
Labels: bug, language: go

#2064 Bump gems via `bundle update`
  Gemfile.lock
Labels: dependencies, ruby

#2068 [RuboCop] Make feature spec stable
  test/smokes/rubocop/expectations.rb
  test/smokes/rubocop/plugins/Gemfile
Labels: language: ruby

#2067 [remark-lint] Add file path to error message
  CHANGELOG.md
  lib/runners/processor/remark_lint.rb
Labels: language: markdown

#2069 Update Dependabot configuration
  .github/dependabot.yml
Labels: dx

#2076 [remark-lint] Add rule ID to error message
  CHANGELOG.md
  lib/runners/processor/remark_lint.rb
Labels: language: markdown

#2077 Avoid link including `master`
  lib/runners/processor/remark_lint.rb
Labels: refactoring

#2079 Bump gems via `bundle update`
  Gemfile.lock
  test/smokes/stylelint/expectations.rb
Labels: dependencies, language: ruby

#1619 [Checkstyle] Provide Sider's recommended set of rules
  CHANGELOG.md
  images/checkstyle/Dockerfile
  images/checkstyle/Dockerfile.erb
  images/checkstyle/sider_recommended_checkstyle.xml
  lib/runners/processor/checkstyle.rb
  lib/runners/recommended_config.rb
  sig/runners/processor/checkstyle.rbs
  sig/runners/recommended_config.rbs
  steep_expectations.yml
  test/smokes/checkstyle/default_rules/sider.yml
  test/smokes/checkstyle/default_rules/src/Hello.java
  test/smokes/checkstyle/expectations.rb
Labels: enhancement, language: java

#2083 Refactor Dockerfiles via `Bundler.locked_gems`
  images/Dockerfile.base.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/golangci_lint/Dockerfile
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/metrics_codeclone/Dockerfile
  images/metrics_complexity/Dockerfile
  images/metrics_fileinfo/Dockerfile
  images/misspell/Dockerfile
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/shellcheck/Dockerfile
  images/slim_lint/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
Labels: refactoring

#1980 [Flake8] Provide Sider's recommended set of rules
  CHANGELOG.md
  images/flake8/sider_recommended_flake8.ini
  test/smokes/flake8/expectations.rb
Labels: enhancement, language: python

#2084 [PHPCS] Provide Sider's recommended set of rules
  CHANGELOG.md
  images/code_sniffer/sider_recommended_code_sniffer.xml
  images/code_sniffer/sider_recommended_code_sniffer_ext.xml
Labels: enhancement, language: php

#2092 Remove unused code about `sider.yml` for `metrics_*` runners
  lib/runners/processor/metrics_complexity.rb
  lib/runners/processor/metrics_fileinfo.rb
  sig/runners/processor/metrics_complexity.rbs
  sig/runners/processor/metrics_fileinfo.rbs
  test/config_test.rb
  test/smokes/metrics_complexity/expectations.rb
  test/smokes/metrics_complexity/root_dir/example.c
  test/smokes/metrics_complexity/root_dir/sider.yml
  test/smokes/metrics_complexity/root_dir/src/baz/こんにちは.py
  test/smokes/metrics_complexity/success/src/baz/fizzbuzz.py
  test/smokes/metrics_complexity/success/src/baz/qux/今日は世界.go
  test/smokes/metrics_complexity/success/src/foo/こんにちは世界.cs
Labels: refactoring

#2097 Rename RuboCop organization: rubocop-hq -> rubocop
  README.md
  analyzers.yml
  lib/runners/processor/rubocop.rb
  lib/runners/rubocop_utils.rb
  test/rubocop_utils_test.rb
  test/ruby_test.rb
  test/smokes/rubocop/unexpected_error/backtrace_silencers.rb
Labels: language: ruby

#2098 Improve RBS via `singleton`
  sig/runners/cli.rbs
  sig/runners/harness.rbs
  sig/runners/processor.rbs
Labels: refactoring

#2099 Remove *removed* Go tools from `sider.yml`
  CHANGELOG.md
  lib/runners/config.rb
  lib/runners/processor.rb
  sig/runners/processor.rbs
  steep_expectations.yml
  test/config_test.rb
  test/smokes/golangci_lint/deprecated_tools/sider.yml
  test/smokes/golangci_lint/expectations.rb
Labels: deprecation, language: go

#2101 Bundle update
  Gemfile.lock
Labels: dependencies, language: ruby

#2100 [Metrics FileInfo] Modify target file generation
  CHANGELOG.md
  lib/runners/processor/metrics_fileinfo.rb
  sig/runners/processor/metrics_fileinfo.rbs
  test/smokes/metrics_fileinfo/expectations.rb
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/COMMIT_EDITMSG
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/HEAD
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/config
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/description
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/hooks/applypatch-msg.sample
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/hooks/commit-msg.sample
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/hooks/fsmonitor-watchman.sample
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/hooks/post-update.sample
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/hooks/pre-applypatch.sample
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/hooks/pre-commit.sample
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/hooks/pre-merge-commit.sample
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/hooks/pre-push.sample
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/hooks/pre-rebase.sample
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/hooks/pre-receive.sample
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/hooks/prepare-commit-msg.sample
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/hooks/update.sample
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/index
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/info/exclude
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/logs/HEAD
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/logs/refs/heads/master
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/04/502b252163663b6fbb3a4a7d70a450ef85a6fb
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/10/fa14c5ab0134436e2ae435138bf921eb477c60
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/14/ed0aa42de0f291c0f696922110e70544c3dae2
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/25/ad77d40188d0bdafec6f5241b2012fff0f680b
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/39/9eab1924e39da570b389b0bef1ca713b3b05c3
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/41/42082bcb939bbc17985a69ba748491ac6b62a5
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/49/8b267a8c7812490d6479839c5577eaaec79d62
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/50/14c4b31cb9700dbd458c8841d8cd91d3b8773c
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/51/5f4836297fdf7567c066983c16e5eff598f7bd
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/61/87dbf4390fc6e28445dd3d988aefb9d1111988
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/6c/bef5c370d8c3486ca85423dd70440c5e0a2aa2
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/7e/ed95d17a6a4843c761edfcc6dbd451ee1d9d9f
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/81/0eecb7e7ac0b9f175b2bbcec6623507ed3b08d
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/9f/e6d5c0318068216003c69d9cd00ddb273fdda0
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/a1/fd29ec14823d8bc4a8d1a2cfe35451580f5118
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/a5/196d1be8fb59edf8062bef36d3a602e0812139
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/a5/d7b84a673458d14d9aab082183a1968c2c7492
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/b5/8d1184a9d43a39c0d95f32453efc78581877d6
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/cb/089cd89a7d7686d284d8761201649346b5aa1c
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/e1/44712c85c055bcf3248ab342592b440a477062
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/ec/17ec1939b7c3e86b7cb6c0c4de6b0818a7e75e
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/objects/fe/09f5a7f04cb214c9d8a7b35594d9c454d15dbd
  test/smokes/metrics_fileinfo/with_ignore_setting/gitmetadata/refs/heads/master
  test/smokes/metrics_fileinfo/with_ignore_setting/hello.rb
  test/smokes/metrics_fileinfo/with_ignore_setting/ignored_dir/ignored_hello.rb
  test/smokes/metrics_fileinfo/with_ignore_setting/sider.yml
Labels: bug, oriental
