Repository sider/runners, pull requests merged in 2021-07, with the labels that each got.

#2496 Bump devon_rex images from 2.45.1 to 2.45.2
  CHANGELOG.md
  images/Dockerfile.java.erb
  images/Dockerfile.npm.erb
  images/Dockerfile.php.erb
  images/Dockerfile.python.erb
  images/Dockerfile.ruby.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/clang_tidy/Dockerfile.erb
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/fxcop/Dockerfile.erb
  images/golangci_lint/Dockerfile
  images/golangci_lint/Dockerfile.erb
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/hadolint/Dockerfile.erb
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/javasee/Dockerfile.erb
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/languagetool/Dockerfile.erb
  images/metrics_codeclone/Dockerfile
  images/metrics_complexity/Dockerfile
  images/metrics_fileinfo/Dockerfile
  images/metrics_fileinfo/Dockerfile.erb
  images/misspell/Dockerfile
  images/misspell/Dockerfile.erb
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/secret_scan/Dockerfile
  images/shellcheck/Dockerfile
  images/shellcheck/Dockerfile.erb
  images/slim_lint/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/swiftlint/Dockerfile.erb
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
Labels: dependencies

#2498 Add document URL to metrics runners
  CHANGELOG.md
  README.md
  analyzers.yml
Labels: documentation, metrics

#2499 Fix `npm install` error with `dependencies` option and private dependencies
  CHANGELOG.md
  images/eslint/package.json
  lib/runners/nodejs.rb
  test/rubocop_utils_test.rb
  test/smokes/eslint/expectations.rb
  test/smokes/eslint/private_dependencies/package.json
  test/smokes/eslint/private_dependencies_with_option_dependencies/package.json
  test/smokes/eslint/private_dependencies_with_option_dependencies/sider.yml
Labels: bug, priority: high

#2511 Temporary fix for RuboCopUtilsTest
  test/rubocop_utils_test.rb
Labels: dx

#2513 [Cppcheck] Optimize installation
  CHANGELOG.md
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
Labels: language: c/c++, performance

#2516 [Querly] Report syntax error as warning
  CHANGELOG.md
  lib/runners/processor/querly.rb
  test/smokes/querly/expectations.rb
  test/smokes/querly/syntax_error/a.rb
  test/smokes/querly/syntax_error/lib/b.rb
  test/smokes/querly/syntax_error/querly.yml
Labels: bug, language: ruby

#2517 Fix ignore patterns on sider.yml
  sider.yml
Labels: dx

#2519 [Metrics File Info] Improve text files extraction
  CHANGELOG.md
  lib/runners/processor/metrics_fileinfo.rb
  sig/runners/processor/metrics_fileinfo.rbs
Labels: metrics, performance

#2520 [Querly] Sort warnings
  CHANGELOG.md
  lib/runners/processor/querly.rb
Labels: bug, language: ruby

#2521 [Querly] Include file path to warning message
  CHANGELOG.md
  lib/runners/processor/querly.rb
  test/smokes/querly/expectations.rb
Labels: bug, language: ruby

#2522 [Metrics File Info] Improve `git log --numstat` speed
  CHANGELOG.md
  lib/runners/harness.rb
  lib/runners/workspace.rb
  lib/runners/workspace/git.rb
  sig/runners/workspace.rbs
  sig/runners/workspace/git.rbs
Labels: metrics, performance

#2524 Bundle update
  Gemfile.lock
Labels: dependencies, language: ruby

#2526 [Metrics File Info] Fix parsing git-ls-files(1) output
  CHANGELOG.md
  lib/runners/processor/metrics_fileinfo.rb
  test/smokes/metrics_fileinfo/expectations.rb
  test/smokes/metrics_fileinfo/gitattributes/.foorc
  test/smokes/metrics_fileinfo/gitattributes/.gitattributes
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/COMMIT_EDITMSG
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/HEAD
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/config
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/description
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/applypatch-msg.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/commit-msg.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/fsmonitor-watchman.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/post-update.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/pre-applypatch.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/pre-commit.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/pre-merge-commit.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/pre-push.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/pre-rebase.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/pre-receive.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/prepare-commit-msg.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/push-to-checkout.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/hooks/update.sample
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/index
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/info/exclude
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/logs/HEAD
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/logs/refs/heads/main
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/objects/1f/e247887b084b684f8fcaf7c9533b099b5be046
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/objects/5f/344dad802e30fce4f8b84e094a52a0a3c1ef9a
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/objects/cd/f4687bd0f1825e0358a084bc3b918ee5ee874c
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/objects/d5/dd18c18920cb54ee440f6889fc3a1d9edad636
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/objects/f2/f44947f80082f93a9a8d8c14582a4cda72a83f
  test/smokes/metrics_fileinfo/gitattributes/gitmetadata/refs/heads/main
  test/smokes/metrics_fileinfo/gitattributes/readme.md
Labels: bug, metrics, priority: high

#2527 [hadolint] Fix `target` option with glob
  CHANGELOG.md
  lib/runners/processor/hadolint.rb
  sig/runners/processor/hadolint.rbs
  steep_expectations.yml
  test/smokes/hadolint/expectations.rb
  test/smokes/hadolint/option_target_glob/Dockerfile
  test/smokes/hadolint/option_target_glob/Dockerfile.production
  test/smokes/hadolint/option_target_glob/bar/Dockerfile
  test/smokes/hadolint/option_target_glob/docker/Dockerfile
  test/smokes/hadolint/option_target_glob/docker/foo/Dockerfile
  test/smokes/hadolint/option_target_glob/empty_Dockerfile
  test/smokes/hadolint/option_target_glob/sider.yml
Labels: bug, language: misc, priority: high

#2528 Bump sider/goodcheck-rules from v0.0.1 to v0.0.2
  goodcheck.yml
Labels: dx

#2530 Bump aufgaben from 0.7.1 to 0.8.2
  Gemfile
  Gemfile.lock
Labels: dependencies, language: ruby

#2525 [PMD CPD] Remove codefragment from results
  CHANGELOG.md
  lib/runners/processor/pmd_cpd.rb
  sig/runners/processor/pmd_cpd.rbs
  steep_expectations.yml
  test/smokes/pmd_cpd/expectations.rb
Labels: language: misc, performance

#2474 [Cppcheck] Enable Sider's recommended set of rules and add `suppressions-list` option
  CHANGELOG.md
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
  lib/runners/processor/cppcheck.rb
  sig/runners/processor/cppcheck.rbs
  test/config_generator_test.rb
  test/data/test_generate_with_tools.yml
  test/smokes/cppcheck/expectations.rb
  test/smokes/cppcheck/suppressions_list/cfg/suppressions.txt
  test/smokes/cppcheck/suppressions_list/sider.yml
  test/smokes/cppcheck/suppressions_list/src/not_good.c
Labels: enhancement, language: c/c++

#2536 [PHPMD] Enable Sider's recommended set of rules
  CHANGELOG.md
  images/phpmd/Dockerfile
  images/phpmd/Dockerfile.erb
  lib/runners/processor/phpmd.rb
  test/smokes/phpmd/expectations.rb
  test/smokes/phpmd/success/app.php
Labels: enhancement, language: php

#2537 Bump devon_rex images from 2.45.2 to 2.45.3
  .ruby-version
  CHANGELOG.md
  Gemfile.lock
  images/Dockerfile.java.erb
  images/Dockerfile.npm.erb
  images/Dockerfile.php.erb
  images/Dockerfile.python.erb
  images/Dockerfile.ruby.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/clang_tidy/Dockerfile.erb
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/fxcop/Dockerfile.erb
  images/golangci_lint/Dockerfile
  images/golangci_lint/Dockerfile.erb
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/hadolint/Dockerfile.erb
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/javasee/Dockerfile.erb
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/languagetool/Dockerfile.erb
  images/metrics_codeclone/Dockerfile
  images/metrics_complexity/Dockerfile
  images/metrics_fileinfo/Dockerfile
  images/metrics_fileinfo/Dockerfile.erb
  images/misspell/Dockerfile
  images/misspell/Dockerfile.erb
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/secret_scan/Dockerfile
  images/shellcheck/Dockerfile
  images/shellcheck/Dockerfile.erb
  images/slim_lint/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/swiftlint/Dockerfile.erb
  images/tyscan/Dockerfile
  runners.gemspec
Labels: dependencies, language: ruby

#2538 Use headings on pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dx

#2539 More relax `required_ruby_version`
  CHANGELOG.md
  runners.gemspec
Labels: dependencies, language: ruby

#2540 Bump goodcheck-rules from 0.0.2 to 0.0.3
  goodcheck.yml
Labels: dx

#2549 [Metrics File Info] Fix unicode filepath
  CHANGELOG.md
  lib/runners/processor/metrics_fileinfo.rb
  test/smokes/metrics_fileinfo/expectations.rb
  test/smokes/metrics_fileinfo/unicode_filepath/<img onerror="alert('ok')" src="foo.png">.js
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/COMMIT_EDITMSG
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/HEAD
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/config
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/description
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/applypatch-msg.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/commit-msg.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/fsmonitor-watchman.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/post-update.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/pre-applypatch.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/pre-commit.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/pre-merge-commit.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/pre-push.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/pre-rebase.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/pre-receive.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/prepare-commit-msg.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/push-to-checkout.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/hooks/update.sample
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/index
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/info/exclude
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/logs/HEAD
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/logs/refs/heads/main
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/objects/0d/8761042ada7a139405b56008c6a8429c7ac4cd
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/objects/27/264ddd2f8613189734efde6596e467e26cfbd5
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/objects/56/1f6d8949d0b3b8c567de1a3efb428dea2de83e
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/objects/6a/8b29b9a10569a847a908a011e763e013937df6
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/objects/83/668ea397833c04bfab68a7919879ae9bd18b24
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/objects/d9/63cd28a83b412709222b9bc11e9a60de1ca251
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391
  test/smokes/metrics_fileinfo/unicode_filepath/gitmetadata/refs/heads/main
  test/smokes/metrics_fileinfo/unicode_filepath/goodcheck copy.yml
  test/smokes/metrics_fileinfo/unicode_filepath/master-test/📁/second_depth_file.js
  test/smokes/metrics_fileinfo/unicode_filepath/master-test/🗄️.js
  test/smokes/metrics_fileinfo/unicode_filepath/zzzzz;' SHOW TABLES; SELECT '.txt
Labels: bug, metrics

#2551 Bump devon_rex images from 2.45.3 to 2.45.4
  CHANGELOG.md
  Gemfile.lock
  images/Dockerfile.java.erb
  images/Dockerfile.npm.erb
  images/Dockerfile.php.erb
  images/Dockerfile.python.erb
  images/Dockerfile.ruby.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/clang_tidy/Dockerfile.erb
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cppcheck/Dockerfile.erb
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/fxcop/Dockerfile.erb
  images/golangci_lint/Dockerfile
  images/golangci_lint/Dockerfile.erb
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/hadolint/Dockerfile.erb
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/javasee/Dockerfile.erb
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/languagetool/Dockerfile.erb
  images/metrics_codeclone/Dockerfile
  images/metrics_complexity/Dockerfile
  images/metrics_fileinfo/Dockerfile
  images/metrics_fileinfo/Dockerfile.erb
  images/misspell/Dockerfile
  images/misspell/Dockerfile.erb
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/secret_scan/Dockerfile
  images/shellcheck/Dockerfile
  images/shellcheck/Dockerfile.erb
  images/slim_lint/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/swiftlint/Dockerfile.erb
  images/tyscan/Dockerfile
Labels: dependencies

#2552 Bundle update
  Gemfile.lock
Labels: dependencies, language: ruby

#2529 Move Secret Scan from Beta
  CHANGELOG.md
  README.md
  analyzers.yml
Labels: language: misc

#2566 Fix wrong Changelog of Secret Scan
  CHANGELOG.md
Labels: documentation

#2567 Fix broken links on ChangeLog
  CHANGELOG.md
Labels: documentation

#2568 Add RuboCop action for Code Scanning
  .github/workflows/rubocop.yml
Labels: dx
