Repository sider/runners, pull requests merged in 2021-03, with the labels that each got.

#2103 [GolangCI-Lint] Remove `DEFAULT_TARGET`
  CHANGELOG.md
  lib/runners/processor/golangci_lint.rb
  sig/runners/processor/golangci_lint.rbs
Labels: language: go

#2119 Bump aws-sdk-s3 from 1.88.1 to 1.89.0
  Gemfile.lock
Labels: dependencies, language: ruby

#2120 [PMD Java] Refactor `Runners::Processor::PmdJava` class
  lib/runners/processor/pmd_java.rb
  sig/runners/processor/pmd_java.rbs
Labels: language: java, refactoring

#2125 Bundle update
  Gemfile.lock
Labels: dependencies, language: ruby

#2127 [Metrics FileInfo] refine log output
  CHANGELOG.md
  lib/runners/processor/metrics_fileinfo.rb
Labels: language: misc, metrics, refactoring

#2129 [GolangCI-Lint] Set explicitly `GO111MODULE=auto`
  CHANGELOG.md
  images/golangci_lint/Dockerfile
  images/golangci_lint/Dockerfile.erb
Labels: language: go

#2132 [PHPCS] Re-consider options
  CHANGELOG.md
  lib/runners/processor/code_sniffer.rb
  sig/runners/processor/code_sniffer.rbs
  test/config_generator_test.rb
  test/data/test_generate_with_tools.yml
  test/smokes/code_sniffer/expectations.rb
  test/smokes/code_sniffer/option_parallel/a.php
  test/smokes/code_sniffer/option_parallel/b.php
  test/smokes/code_sniffer/option_parallel/sider.yml
  test/smokes/code_sniffer/phpcs3/custom_argument/sideci.yml
  test/smokes/code_sniffer/phpcs3/expectations.rb
  test/smokes/code_sniffer/specified_dir/sideci.yml
  test/smokes/code_sniffer/specified_dir/test/test.php
Labels: deprecation

#2135 Fix `rake bump:analyzers`
  tasks/bump/analyzers.rake
Labels: bug, dx

#2146 [Metrics Code Clone] Report the total number of duplicated lines
  CHANGELOG.md
  lib/runners/processor/metrics_codeclone.rb
  test/smokes/metrics_codeclone/expectations.rb
Labels: enhancement, metrics

#2151 Bump bundler from 2.2.13 to 2.2.14
  Gemfile.lock
  runners.gemspec
Labels: dependencies, language: ruby

#2150 Install default npm dependencies via npm 7
  CHANGELOG.md
  images/Dockerfile.npm.erb
  images/coffeelint/Dockerfile
  images/eslint/Dockerfile
  images/eslint/package.json
  images/jshint/Dockerfile
  images/remark_lint/Dockerfile
  images/stylelint/Dockerfile
  images/stylelint/package.json
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
  images/tyscan/package.json
Labels: dependencies, language: javascript

#2154 Bump Clang-Tidy from 10 to 11
  CHANGELOG.md
  images/clang_tidy/Dockerfile
  images/clang_tidy/Dockerfile.erb
  test/smokes/clang_tidy/expectations.rb
Labels: dependencies, language: c/c++

#2137 [Checkstyle] Enable Sider's recommended set of rules
  CHANGELOG.md
  lib/runners/processor/checkstyle.rb
  test/smokes/checkstyle/expectations.rb
  test/smokes/checkstyle/google/sider.yml
  test/smokes/checkstyle/google/src/Hello.java
Labels: enhancement, language: java

#2156 Bump rbs and steep
  Gemfile.lock
  Steepfile
  lib/runners/processor/metrics_codeclone.rb
  sig/rubygems.rbs
  sig/runners/ruby/gem_installer/source.rbs
  steep_expectations.yml
Labels: dependencies, language: ruby

#2158 Bump amazing_print from 1.2.2 to 1.3.0
  Gemfile.lock
Labels: dependencies, language: ruby

#2157 [Flake8] Enable Sider's recommended set of rules
  CHANGELOG.md
  images/flake8/Dockerfile
  images/flake8/Dockerfile.erb
  test/smokes/flake8/expectations.rb
Labels: enhancement, language: python

#2160 Replace `Runners::Nodejs::Constraint` with `Gem::Requirement`
  lib/runners.rb
  lib/runners/nodejs.rb
  lib/runners/nodejs/constraint.rb
  lib/runners/nodejs/dependency.rb
  lib/runners/processor/coffeelint.rb
  lib/runners/processor/eslint.rb
  lib/runners/processor/remark_lint.rb
  lib/runners/processor/stylelint.rb
  lib/runners/processor/tslint.rb
  lib/runners/processor/tyscan.rb
  sig/rubygems.rbs
  sig/runners/nodejs.rbs
  sig/runners/nodejs/constraint.rbs
  sig/runners/nodejs/dependency.rbs
  test/nodejs_test.rb
Labels: language: javascript, refactoring

#2161 Refactor `Runners::Nodejs#install_nodejs_deps` method
  lib/runners/nodejs.rb
  lib/runners/processor/coffeelint.rb
  lib/runners/processor/eslint.rb
  lib/runners/processor/remark_lint.rb
  lib/runners/processor/stylelint.rb
  lib/runners/processor/tslint.rb
  lib/runners/processor/tyscan.rb
  sig/runners/nodejs.rbs
Labels: dependencies, refactoring

#2162 Add `Runners::Nodejs::PACKAGE_JSON`
  lib/runners/nodejs.rb
  sig/runners/nodejs.rbs
Labels: language: javascript, refactoring

#2163 Use `Gem::Requirement` for Ruby runners
  lib/runners/processor/brakeman.rb
  lib/runners/processor/coffeelint.rb
  lib/runners/processor/eslint.rb
  lib/runners/processor/goodcheck.rb
  lib/runners/processor/haml_lint.rb
  lib/runners/processor/querly.rb
  lib/runners/processor/rails_best_practices.rb
  lib/runners/processor/reek.rb
  lib/runners/processor/remark_lint.rb
  lib/runners/processor/rubocop.rb
  lib/runners/processor/slim_lint.rb
  lib/runners/processor/stylelint.rb
  lib/runners/processor/tslint.rb
  lib/runners/processor/tyscan.rb
  lib/runners/ruby.rb
  lib/runners/ruby/gem_installer.rb
  sig/rubygems.rbs
  sig/runners/processor/rubocop.rbs
  sig/runners/ruby.rbs
  sig/runners/ruby/gem_installer.rbs
  test/ruby_test.rb
Labels: language: ruby, refactoring

#2164 Inline `Runners::Ruby#installed_gem_versions` method
  lib/runners/ruby.rb
  sig/runners/ruby.rbs
  test/ruby_test.rb
Labels: language: ruby, refactoring

#2166 Move `Runners::GemInstaller::Spec.from_gems` into `Runners::Ruby`
  lib/runners/ruby.rb
  lib/runners/ruby/gem_installer/spec.rb
  sig/runners/ruby.rbs
  sig/runners/ruby/gem_installer.rbs
  sig/runners/ruby/gem_installer/source.rbs
  sig/runners/ruby/gem_installer/spec.rbs
  steep_expectations.yml
  test/ruby_test.rb
Labels: language: ruby, refactoring

#2167 Move `Runners::GemInstaller::Spec.merge` into `Runners::Ruby`
  lib/runners/ruby.rb
  lib/runners/ruby/gem_installer/spec.rb
  sig/runners/ruby.rbs
  sig/runners/ruby/gem_installer/spec.rbs
  steep_expectations.yml
  test/ruby_test.rb
Labels: language: ruby, refactoring

#2168 Simplify generated `Gemfile`
  CHANGELOG.md
  lib/runners/ruby.rb
  lib/runners/ruby/gem_installer.rb
  lib/runners/ruby/gem_installer/source.rb
  sig/runners/ruby/gem_installer.rbs
  sig/runners/ruby/gem_installer/source.rbs
  steep_expectations.yml
  test/ruby_test.rb
Labels: language: ruby

#2169 Refactor `Runners::GemInstaller::Spec`
  lib/runners/processor/haml_lint.rb
  lib/runners/processor/querly.rb
  lib/runners/processor/rails_best_practices.rb
  lib/runners/processor/rubocop.rb
  lib/runners/processor/slim_lint.rb
  lib/runners/rubocop_utils.rb
  lib/runners/ruby.rb
  lib/runners/ruby/gem_installer.rb
  lib/runners/ruby/gem_installer/spec.rb
  lib/runners/ruby/lockfile_loader/lockfile.rb
  sig/runners/ruby/gem_installer/spec.rbs
  sig/runners/ruby/lockfile_loader/lockfile.rbs
  steep_expectations.yml
  test/ruby_test.rb
  test/smokes/rails_best_practices/expectations.rb
  test/smokes/reek/expectations.rb
  test/smokes/rubocop/expectations.rb
Labels: language: ruby, refactoring

#2170 Revert skipped test case in rubocop_utils_test.rb
  test/rubocop_utils_test.rb
Labels: refactoring

#2172 Refactor `GemInstaller#install!` method
  lib/runners/ruby/gem_installer.rb
  sig/runners/ruby.rbs
  sig/runners/ruby/gem_installer.rbs
  test/ruby_test.rb
Labels: language: ruby, refactoring

#2179 Remove needless Goodcheck rule for TypeScript ESLint
  goodcheck.yml
Labels: dependencies, language: javascript, refactoring

#2180 [Flake8] Simplify `Runners::Processor::Flake8` a bit
  lib/runners/processor/flake8.rb
  sig/runners/processor/flake8.rbs
Labels: language: python, refactoring

#2181 [Flake8] Use default formatter
  CHANGELOG.md
  lib/runners/processor/flake8.rb
  sig/runners/processor/flake8.rbs
Labels: language: python

#2182 [PHPCS] Enable Sider's recommended set of rules
  CHANGELOG.md
  images/code_sniffer/Dockerfile
  images/code_sniffer/Dockerfile.erb
  lib/runners/processor/code_sniffer.rb
  sig/runners/processor/code_sniffer.rbs
  test/smokes/code_sniffer/expectations.rb
  test/smokes/code_sniffer/success/app.php
Labels: enhancement, language: php

#2186 Bump gems via `bundle update`
  Gemfile.lock
Labels: dependencies, language: ruby

#2171 Loosen unsatisfied constraints for npm packages
  CHANGELOG.md
  lib/runners/nodejs.rb
  sig/runners/nodejs.rbs
  test/nodejs_test.rb
  test/smokes/eslint/expectations.rb
  test/smokes/eslint/pinned_old_eslint/src/index.js
  test/smokes/stylelint/expectations.rb
  test/smokes/stylelint/pinned_stylelint_version/.stylelintrc.yaml
  test/smokes/stylelint/pinned_stylelint_version/test.css
  test/smokes/stylelint/pinned_stylelint_version/test.scss
  test/smokes/tslint/expectations.rb
  test/smokes/tyscan/expectations.rb
Labels: language: javascript

#2188 Refactor NodejsTest
  test/nodejs_test.rb
Labels: refactoring

#2193 Remove `linter.scss_lint.options`
  CHANGELOG.md
  lib/runners/processor/scss_lint.rb
  test/smokes/scss_lint/with_config_option/sideci.yml
Labels: deprecation

#2194 Secure `pip install`
  CHANGELOG.md
  lib/runners/python.rb
  sig/runners/python.rbs
  test/smokes/flake8/expectations.rb
  test/smokes/flake8/with_plugins_failed/sider.yml
Labels: language: python, security

#2196 Small refactoring for #2191
  lib/runners/processor/cppcheck.rb
Labels: refactoring

#2165 [ESLint] Provide Sider's recommended set of rules
  CHANGELOG.md
  images/eslint/sider_recommended_eslint.yml
Labels: enhancement, language: javascript

#2199 [ESLint] Use `--no-error-on-unmatched-pattern` if possible
  CHANGELOG.md
  lib/runners/processor/eslint.rb
  test/smokes/eslint/expectations.rb
  test/smokes/eslint/no_files_with_option_target/sider.yml
Labels: language: javascript

#2200 Refactor `Runners::Nodejs` class
  lib/runners/nodejs.rb
  sig/runners/nodejs.rbs
Labels: refactoring

#2201 [PHPMD] Handle syntax error as issue
  CHANGELOG.md
  lib/runners/processor/phpmd.rb
  test/smokes/phpmd/expectations.rb
Labels: language: php

#2206 [ktlint] Add issue ID for syntax error
  CHANGELOG.md
  lib/runners/processor/ktlint.rb
  test/smokes/ktlint/expectations.rb
Labels: bug, language: kotlin

#2209 Use `Gem::Version.new` to fix Steep errors
  lib/runners/processor.rb
  lib/runners/processor/haml_lint.rb
  lib/runners/processor/reek.rb
  lib/runners/processor/rubocop.rb
  lib/runners/processor/stylelint.rb
  steep_expectations.yml
Labels: refactoring

#2210 [Clang-Tidy] Better `apt-get install` failure
  CHANGELOG.md
  lib/runners/cplusplus.rb
  sig/runners/cplusplus.rbs
  test/smokes/clang_tidy/expectations.rb
  test/smokes/clang_tidy/invalid_apt_package_name/sider.yml
  test/smokes/clang_tidy/invalid_apt_package_version/sider.yml
Labels: language: c/c++

#2212 [CoffeeLint] Set deadline for older versions
  CHANGELOG.md
  lib/runners/processor/coffeelint.rb
  test/smokes/coffeelint/expectations.rb
Labels: deprecation, language: javascript

#2215 [TSLint] Extend deadline and add helpful link
  CHANGELOG.md
  lib/runners/processor/tslint.rb
  test/smokes/tslint/expectations.rb
Labels: deprecation, language: javascript

#2216 Add `Runners::Warnings` class
  lib/runners.rb
  lib/runners/cli.rb
  lib/runners/harness.rb
  lib/runners/processor.rb
  lib/runners/processor/coffeelint.rb
  lib/runners/processor/eslint.rb
  lib/runners/processor/haml_lint.rb
  lib/runners/processor/misspell.rb
  lib/runners/processor/scss_lint.rb
  lib/runners/processor/tslint.rb
  lib/runners/warnings.rb
  sig/runners/config.rbs
  sig/runners/harness.rbs
  sig/runners/processor.rbs
  sig/runners/warnings.rbs
  steep_expectations.yml
  test/nodejs_test.rb
  test/processor_test.rb
  test/ruby_test.rb
  test/smokes/coffeelint/expectations.rb
  test/smokes/eslint/expectations.rb
  test/smokes/haml_lint/expectations.rb
  test/smokes/misspell/expectations.rb
  test/smokes/scss_lint/expectations.rb
  test/smokes/tslint/expectations.rb
  test/warnings_test.rb
Labels: deprecation, refactoring

#2218 Pass `--force` flag to `npm install`
  CHANGELOG.md
  lib/runners/nodejs.rb
  test/nodejs_test.rb
  test/smokes/eslint/expectations.rb
  test/smokes/eslint/unmet_peer_deps/package.json
Labels: bug, dependencies, language: javascript

#2219 Simplify `Runners::Processor.register_config_schema` method
  lib/runners/processor.rb
  lib/runners/processor/brakeman.rb
  lib/runners/processor/checkstyle.rb
  lib/runners/processor/clang_tidy.rb
  lib/runners/processor/code_sniffer.rb
  lib/runners/processor/coffeelint.rb
  lib/runners/processor/cppcheck.rb
  lib/runners/processor/cpplint.rb
  lib/runners/processor/detekt.rb
  lib/runners/processor/eslint.rb
  lib/runners/processor/flake8.rb
  lib/runners/processor/fxcop.rb
  lib/runners/processor/golangci_lint.rb
  lib/runners/processor/goodcheck.rb
  lib/runners/processor/hadolint.rb
  lib/runners/processor/haml_lint.rb
  lib/runners/processor/javasee.rb
  lib/runners/processor/jshint.rb
  lib/runners/processor/ktlint.rb
  lib/runners/processor/languagetool.rb
  lib/runners/processor/misspell.rb
  lib/runners/processor/phinder.rb
  lib/runners/processor/phpmd.rb
  lib/runners/processor/pmd_cpd.rb
  lib/runners/processor/pmd_java.rb
  lib/runners/processor/pylint.rb
  lib/runners/processor/querly.rb
  lib/runners/processor/rails_best_practices.rb
  lib/runners/processor/reek.rb
  lib/runners/processor/remark_lint.rb
  lib/runners/processor/rubocop.rb
  lib/runners/processor/scss_lint.rb
  lib/runners/processor/shellcheck.rb
  lib/runners/processor/slim_lint.rb
  lib/runners/processor/stylelint.rb
  lib/runners/processor/swiftlint.rb
  lib/runners/processor/tslint.rb
  lib/runners/processor/tyscan.rb
  sig/runners/processor.rbs
  steep_expectations.yml
Labels: refactoring

#2220 Refactor use of `Runners::Tmpdir` module
  lib/runners/processor.rb
  lib/runners/ruby.rb
  lib/runners/tmpdir.rb
  sig/runners/processor.rbs
  sig/runners/tmpdir.rbs
  steep_expectations.yml
Labels: refactoring

#2221 `Runners::Config` check warnings
  CHANGELOG.md
  lib/runners/config.rb
  lib/runners/processor.rb
  lib/runners/processor/eslint.rb
  lib/runners/processor/haml_lint.rb
  lib/runners/processor/misspell.rb
  lib/runners/warnings.rb
  sig/runners/config.rbs
  sig/runners/processor.rbs
  sig/runners/warnings.rbs
  steep_expectations.yml
  test/config_test.rb
  test/warnings_test.rb
Labels: enhancement

#2222 Add `npm install` flags to suppress extra output
  CHANGELOG.md
  lib/runners/nodejs.rb
Labels: language: javascript

#2225 Exclude duplicate warnings in `Runners::Warnings`
  lib/runners/warnings.rb
  sig/runners/warnings.rbs
  test/warnings_test.rb
Labels: bug

#2226 Refactor `Runners::Java` class
  lib/runners/java.rb
  sig/runners/java.rbs
  test/java_test.rb
Labels: refactoring

#2224 [remark-lint] Use `.git` directory and add `remark-validate-links` to default ruleset
  CHANGELOG.md
  images/remark_lint/Dockerfile
  images/remark_lint/Dockerfile.erb
  images/remark_lint/package.json
  images/remark_lint/sider_recommended_remark_lint.yml
  lib/runners/processor/remark_lint.rb
  sig/runners/processor/remark_lint.rbs
  test/smokes/remark_lint/expectations.rb
  test/smokes/remark_lint/success/readme.md
  test/smokes/remark_lint/use_git/foo.md
  test/smokes/remark_lint/use_git_root_dir/sider.yml
  test/smokes/remark_lint/use_git_root_dir/src/foo.md
Labels: enhancement, language: markdown

#2211 Introduce common option `linter.<id>.dependencies`
  CHANGELOG.md
  lib/runners/cplusplus.rb
  lib/runners/java.rb
  lib/runners/ruby.rb
  lib/runners/schema/config.rb
  sig/runners/java.rbs
  sig/runners/schema/config.rbs
  test/ruby_test.rb
  test/smokes/checkstyle/dependencies/Foo.java
  test/smokes/checkstyle/dependencies/checkstyle.xml
  test/smokes/checkstyle/dependencies/sider.yml
  test/smokes/checkstyle/expectations.rb
  test/smokes/clang_tidy/expectations.rb
  test/smokes/clang_tidy/invalid_apt_package_name/sider.yml
  test/smokes/clang_tidy/invalid_apt_package_version/sider.yml
  test/smokes/clang_tidy/option_dependencies/sider.yml
  test/smokes/clang_tidy/option_include_path/sider.yml
  test/smokes/clang_tidy/option_include_path_default/sider.yml
  test/smokes/detekt/dependencies/Foo.kt
  test/smokes/detekt/dependencies/detekt.yml
  test/smokes/detekt/dependencies/sider.yml
  test/smokes/detekt/expectations.rb
  test/smokes/ktlint/expectations.rb
  test/smokes/pmd_java/deps/sider.yml
  test/smokes/rails_best_practices/expectations.rb
  test/smokes/reek/expectations.rb
  test/smokes/rubocop/expectations.rb
  test/smokes/rubocop/sandbox_rails/sider.yml
Labels: deprecation, enhancement

#2234 Delete unused `incorrect_yarn_data`
  test/incorrect_yarn_data/package.json
  test/incorrect_yarn_data/yarn.lock
  test/test_helper.rb
Labels: refactoring

#2235 Fix typo for "satisfied"
  lib/runners/nodejs.rb
  sig/runners/nodejs.rbs
Labels: refactoring

#2236 [ESLint] Allow strings for `ext` and `global` options
  CHANGELOG.md
  lib/runners/processor/eslint.rb
  test/data/test_generate_with_tools.yml
  test/smokes/eslint/expectations.rb
  test/smokes/eslint/option_global/.eslintrc.json
  test/smokes/eslint/option_global/foo.js
  test/smokes/eslint/option_global/sider.yml
  test/smokes/eslint/sider_config/sideci.yml
Labels: enhancement, language: javascript
