Repository sider/runners, pull requests merged in 2021-01, with the labels that each got.

#1879 Prevent Git hooks
  CHANGELOG.md
  lib/runners/workspace/git.rb
  test/workspace/git_test.rb
Labels: security

#1893 Improve `pip install`
  CHANGELOG.md
  lib/runners/processor/flake8.rb
  lib/runners/python.rb
  sig/runners/python.rbs
Labels: language: python

#1896 [Flake8] Add smoke test case for VCS URL
  test/smokes/flake8/expectations.rb
  test/smokes/flake8/with_plugins/foo2.py
  test/smokes/flake8/with_plugins/sideci.yml
Labels: dx

#1897 More data on `Shell::ExecError`
  lib/runners/shell.rb
  sig/runners/shell.rbs
  test/shell_test.rb
Labels: dx

#1898 Commit `Gemfile.lock` on `rake release`
  CHANGELOG.md
  Gemfile.lock
  Rakefile
Labels: dx

#1902 [ESLint] Add `eslint-config-react-app` as pre-installed
  CHANGELOG.md
  images/eslint/package.json
Labels: dependencies, javascript

#1904 Refactor `Runners::Config` class
  lib/runners/config.rb
  lib/runners/harness.rb
  sig/runners/config.rbs
  test/config_test.rb
  test/test_helper.rb
Labels: refactoring

#1906 Stop output `$EXTRA_CERTIFICATE` on debug
  images/docker-entrypoint.sh
Labels: dx

#1900 [Flake8] remove debug code (#1899, #1903, #1908)
  lib/runners/processor/flake8.rb
Labels: bug

#1907 Refactor `Runners::Shell` initialization
  lib/runners/harness.rb
  lib/runners/processor.rb
  lib/runners/shell.rb
  sig/runners/harness.rbs
  sig/runners/processor.rbs
  sig/runners/shell.rbs
  test/harness_test.rb
  test/java_test.rb
  test/nodejs_test.rb
  test/processor/phpmd_test.rb
  test/processor/remark_lint_test.rb
  test/processor/rubocop_test.rb
  test/processor_test.rb
  test/ruby_test.rb
  test/shell_test.rb
Labels: refactoring

#1909 Refactor `Runners::Config` class
  lib/runners/config.rb
  sig/runners/config.rbs
  test/config_test.rb
  test/test_helper.rb
Labels: refactoring

#1913 Add `Runners::Config#exclude_branch?` method
  CHANGELOG.md
  lib/runners/config.rb
  sig/runners/config.rbs
  test/config_test.rb
Labels: enhancement

#1916 Do not use `--no-default-rc` flag for `yarn`
  CHANGELOG.md
  lib/runners/nodejs.rb
  test/nodejs_test.rb
Labels: bug

#1925 [RuboCop] Fix issue links for rubydoc.info
  CHANGELOG.md
  lib/runners/processor/rubocop.rb
  sig/runners/processor/rubocop.rbs
  test/processor/rubocop_test.rb
Labels: bug, language: ruby

#1924 Do not use `Gem::Requirement` in gemspec
  runners.gemspec
Labels: dependencies, refactoring, ruby

#1927 Bump bugsnag from 6.18.0 to 6.19.0
  Gemfile.lock
Labels: dependencies, ruby

#1928 Bump aws-sdk-kms from 1.40.0 to 1.41.0
  Gemfile.lock
Labels: dependencies, ruby

#1917 Relax Bundler requirement
  CHANGELOG.md
  Gemfile.lock
  runners.gemspec
Labels: dependencies, ruby

#1933 Remove TODO comment from smoke.rb
  test/smokes/smoke.rb
Labels: refactoring

#1934 [ESLint] Add `@vue/eslint-config-typescript` to pre-installed packages
  CHANGELOG.md
  images/eslint/package.json
Labels: dependencies, language: javascript

#1936 [ESLint] Add `eslint-plugin-cypress` to pre-installed packages
  CHANGELOG.md
  images/eslint/package.json
Labels: dependencies, javascript, language: javascript

#1939 Re-enable `Lint/EmptyFile` in .rubocop.yml
  .rubocop.yml
Labels: dx

#1940 [Querly] Refactor smoke test a bit
  test/smokes/querly/expectations.rb
Labels: refactoring

#1941 Exclude some files from Goodcheck
  goodcheck.yml
Labels: dx

#1942 [RuboCop] Revert rubydoc.info links
  CHANGELOG.md
  lib/runners/processor/rubocop.rb
  test/processor/rubocop_test.rb
Labels: language: ruby

#1943 Move test/smokes/smoke.rb -> test/smoke.rb
  bin/runners_smoke
  test/smoke.rb
Labels: dx

#1944 Refactor smoke test runner
  bin/.keep
  bin/runners_smoke
  tasks/docker/smoke.rake
  test/smoke.rb
Labels: dx

#1957 [SwiftLint] Remove hack for smoke test on CI
  .github/workflows/build.yml
Labels: dx

#1955 Improve behavior about `Changes` class
  CHANGELOG.md
  lib/runners/changes.rb
  lib/runners/processor.rb
  lib/runners/workspace.rb
  sig/runners/changes.rbs
  test/changes_test.rb
Labels: bug

#1960 Bump bundler from 2.2.3 to 2.2.6
  Gemfile.lock
  images/Dockerfile.base.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/golangci_lint/Dockerfile
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/misspell/Dockerfile
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/shellcheck/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
  runners.gemspec
Labels: dependencies, ruby

#1962 add type signature of time class from rbs v1.0.0
  sig/time.rbs
Labels: language: ruby

#1975 Bump bundler from 2.2.6 to 2.2.7
  CHANGELOG.md
  Gemfile.lock
Labels: dependencies, ruby

#1978 Allow `Pathname` arguments for `Runners::Shell` methods
  lib/runners/shell.rb
  sig/runners/processor.rbs
  sig/runners/shell.rbs
  test/harness_test.rb
  test/shell_test.rb
Labels: refactoring

#1631 Support metrics code complexity
  .github/dependabot.yml
  .github/workflows/build.yml
  CHANGELOG.md
  README.md
  analyzers.yml
  images/metrics_complexity/Dockerfile
  images/metrics_complexity/Dockerfile.erb
  images/metrics_complexity/Pipfile
  lib/runners.rb
  lib/runners/processor/metrics_complexity.rb
  sig/runners/processor/metrics_complexity.rbs
  test/config_test.rb
  test/smokes/metrics_complexity/comma_in_filename/src/example,file.cs
  test/smokes/metrics_complexity/expectations.rb
  test/smokes/metrics_complexity/root_dir/example.c
  test/smokes/metrics_complexity/root_dir/sider.yml
  test/smokes/metrics_complexity/root_dir/src/baz/fizzbuzz.py
  test/smokes/metrics_complexity/root_dir/src/baz/qux/今日は世界.go
  test/smokes/metrics_complexity/root_dir/src/baz/こんにちは.py
  test/smokes/metrics_complexity/root_dir/src/foo/こんにちは世界.cs
  test/smokes/metrics_complexity/success/example.c
  test/smokes/metrics_complexity/success/example.c.txt
  test/smokes/metrics_complexity/success/src/baz/hello.php
  test/smokes/metrics_complexity/success/src/baz/hello.rb
  test/smokes/metrics_complexity/success/src/baz/hello.scala
  test/smokes/metrics_complexity/success/src/baz/qux/hello.lua
  test/smokes/metrics_complexity/success/src/baz/qux/hello.rs
  test/smokes/metrics_complexity/success/src/foo/bar/hello.m
  test/smokes/metrics_complexity/success/src/foo/bar/hello.swift
  test/smokes/metrics_complexity/success/src/foo/hello.c
  test/smokes/metrics_complexity/success/src/foo/hello.cpp
  test/smokes/metrics_complexity/success/src/foo/hello.java
  test/smokes/metrics_complexity/success/src/foo/hello.js
Labels: DO NOT MERGE, enhancement, language: misc

#1983 Bump development gems except for `steep`
  Gemfile.lock
Labels: dependencies, ruby

#1989 Bump bundler minimum version to 2.2.7
  Gemfile.lock
  runners.gemspec
Labels: dependencies, ruby

#1990 Refactor `Runners::Analyzers#content`
  lib/runners/analyzers.rb
  sig/runners/analyzers.rbs
Labels: refactoring
