Repository sider/runners, pull requests merged in 2021-04, with the labels that each got.

#2263 Do not use deprecated options for config example
  CHANGELOG.md
  lib/runners/processor/checkstyle.rb
  lib/runners/processor/clang_tidy.rb
  lib/runners/processor/detekt.rb
  lib/runners/processor/ktlint.rb
  lib/runners/processor/pmd_java.rb
  test/data/test_generate_with_tools.yml
Labels: bug

#2272 [ESLint] Add smoke test case for deprecated and removed rules
  test/smokes/eslint/deprecated_and_removed_rules/foo.js
  test/smokes/eslint/deprecated_and_removed_rules/package.json
  test/smokes/eslint/expectations.rb
Labels: dx

#2273 [Actions] Replace `softprops/action-gh-release` with `gh release`
  .github/workflows/release.yml
Labels: dx

#2277 [Metrics_CodeClone] Fix NoMethodError in `Runners::Processor::MetricsCodeClone#initialize`
  CHANGELOG.md
  lib/runners/harness.rb
  lib/runners/processor.rb
  lib/runners/processor/metrics_codeclone.rb
  sig/runners/processor.rbs
  steep_expectations.yml
  test/java_test.rb
  test/smokes/metrics_codeclone/config_warnings/sider.yml
  test/smokes/metrics_codeclone/expectations.rb
Labels: bug, metrics

#2279 Refactor `Runners::Schema::Config` class
  lib/runners/schema/config.rb
  sig/runners/schema/config.rbs
Labels: refactoring

#2282 [RuboCop] Fix smoke test due to Ruby 2.7.3
  test/smokes/rubocop/expectations.rb
Labels: language: ruby

#2281 [Flake8] Fix `Errno::ENOENT` on multiple configurations
  CHANGELOG.md
  lib/runners/processor/flake8.rb
  test/smokes/flake8/expectations.rb
  test/smokes/flake8/multiple_config_files/setup.cfg
  test/smokes/flake8/multiple_config_files/tox.ini
Labels: bug, language: python

#2283 Bundle update
  Gemfile.lock
Labels: dependencies, language: ruby

#2249 [Metrics Complexity] Add workarounds for lizard's bugs
  CHANGELOG.md
  images/metrics_complexity/Pipfile
  lib/runners/processor/metrics_complexity.rb
  sig/runners/processor/metrics_complexity.rbs
  test/smokes/metrics_complexity/complex_file/test.js
  test/smokes/metrics_complexity/expectations.rb
  test/smokes/metrics_complexity/illegal_char_in_rspec_condition/myclass_test.rb
Labels: bug, metrics

#2250 [ESLint] RE-provide Sider's recommended set of rules
  CHANGELOG.md
  images/eslint/sider_recommended_eslint.js
  images/eslint/sider_recommended_eslint.yml
Labels: enhancement, language: javascript

#2296 [JAVA PMD] Provide Sider's recommended set of rules
  CHANGELOG.md
  images/pmd_java/sider_recommended_pmd.xml
Labels: enhancement, language: java

#2266 [RuboCop] Provide Sider's recommended set of rules
  CHANGELOG.md
  images/rubocop/sider_recommended_rubocop.yml
Labels: enhancement, language: ruby

#2307 [HAML-Lint] Fix smoke test due to RuboCop
  test/smokes/haml_lint/plain-rubocop/.rubocop.yml
Labels: language: ruby

#2306 [ShellCheck] Refactor Dockerfile
  images/shellcheck/Dockerfile
  images/shellcheck/Dockerfile.erb
Labels: language: misc, refactoring

#2308 Refactor Dockerfiles using `$RUNNER_USER_BIN`
  images/golangci_lint/Dockerfile
  images/golangci_lint/Dockerfile.erb
  images/hadolint/Dockerfile
  images/hadolint/Dockerfile.erb
  images/javasee/Dockerfile
  images/javasee/Dockerfile.erb
  images/metrics_codeclone/Dockerfile
  images/misspell/Dockerfile
  images/misspell/Dockerfile.erb
  images/pmd_cpd/Dockerfile
  images/pmd_cpd/Dockerfile.erb
  images/pmd_java/Dockerfile
  images/pmd_java/Dockerfile.erb
  images/swiftlint/Dockerfile
  images/swiftlint/Dockerfile.erb
Labels: refactoring

#2309 Refactor getting PMD version
  images/metrics_codeclone/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_cpd/Dockerfile.erb
  images/pmd_java/Dockerfile
  images/pmd_java/Dockerfile.erb
  images/pmd_java/ShowPMDVersion.java
  images/pmd_java/show_pmd_version
  lib/runners/java.rb
  lib/runners/processor/pmd_cpd.rb
  lib/runners/processor/pmd_java.rb
  sig/runners/java.rbs
Labels: language: java, refactoring

#2310 Improve smoke test output's appearance
  test/smoke.rb
Labels: refactoring

#2312 Refactor `docker login` for clarity and simplicity
  .github/workflows/build.yml
  tasks/docker/common.rb
  tasks/docker/push.rake
Labels: refactoring

#2314 Bump rubocop from 1.12.1 to 1.13.0
  Gemfile.lock
Labels: dependencies, language: ruby

#2315 Bump steep from 0.43.1 to 0.44.0
  Gemfile.lock
  sig/rubygems.rbs
Labels: dependencies, language: ruby

#2316 Improve installation of npm dependencies via `sider.yml`
  CHANGELOG.md
  images/Dockerfile.base.erb
  images/brakeman/Dockerfile
  images/checkstyle/Dockerfile
  images/clang_tidy/Dockerfile
  images/code_sniffer/Dockerfile
  images/coffeelint/Dockerfile
  images/cppcheck/Dockerfile
  images/cpplint/Dockerfile
  images/detekt/Dockerfile
  images/eslint/Dockerfile
  images/flake8/Dockerfile
  images/fxcop/Dockerfile
  images/golangci_lint/Dockerfile
  images/goodcheck/Dockerfile
  images/hadolint/Dockerfile
  images/haml_lint/Dockerfile
  images/javasee/Dockerfile
  images/jshint/Dockerfile
  images/ktlint/Dockerfile
  images/languagetool/Dockerfile
  images/metrics_codeclone/Dockerfile
  images/metrics_complexity/Dockerfile
  images/metrics_fileinfo/Dockerfile
  images/misspell/Dockerfile
  images/phinder/Dockerfile
  images/phpmd/Dockerfile
  images/pmd_cpd/Dockerfile
  images/pmd_java/Dockerfile
  images/pylint/Dockerfile
  images/querly/Dockerfile
  images/rails_best_practices/Dockerfile
  images/reek/Dockerfile
  images/remark_lint/Dockerfile
  images/rubocop/Dockerfile
  images/scss_lint/Dockerfile
  images/shellcheck/Dockerfile
  images/slim_lint/Dockerfile
  images/stylelint/Dockerfile
  images/swiftlint/Dockerfile
  images/tslint/Dockerfile
  images/tyscan/Dockerfile
  lib/runners/nodejs.rb
  lib/runners/shell.rb
  sig/runners/nodejs.rbs
  sig/runners/processor.rbs
  sig/runners/shell.rbs
  test/nodejs_test.rb
  test/test_helper.rb
Labels: language: javascript

#2318 Refactor `with_stubbed_env` test helper method
  test/test_helper.rb
Labels: refactoring

#2319 Inline `Runners::Nodejs#nodejs_analyzer_local_version` method
  lib/runners/nodejs.rb
  sig/runners/nodejs.rbs
  test/nodejs_test.rb
Labels: refactoring

#2337 Skip unstable Chefstyle assertion
  test/rubocop_utils_test.rb
Labels: dx

#2340 Bundle update
  Gemfile.lock
Labels: dependencies, language: ruby

#2343 Format expectations.rb via RuboCop
  test/smokes/metrics_complexity/expectations.rb
  test/smokes/shellcheck/expectations.rb
Labels: refactoring
