Repository sider/runners, pull requests merged in 2021-11, with the labels that each got.

#2780 Bump git_diff_parser version to 4.0.0
  Gemfile.lock
  runners.gemspec
Labels: bug, dependencies

#2804 Disable auto rebasing by dependabot temporarily
  .github/dependabot.yml
Labels: dx

#2809 Fix failing actionlint smoke tests
  test/smokes/actionlint/expectations.rb
Labels: bug

#2814 Update Sider Scan configuration
  .github/workflows/sider_scan.yml
Labels: dx

#2806 Revert "Disable auto rebasing by dependabot temporarily"
  .github/dependabot.yml
Labels: dx

#2820 [ESLint] Allow ESLint8.x in user dependency
  CHANGELOG.md
  lib/runners/processor/eslint.rb
  test/smokes/eslint/expectations.rb
Labels: dependencies, language: javascript

#2835 Disable dependabot's auto rebasing
  .github/dependabot.yml
Labels: dx
